"""French slide library for Slide Processing exercise."""

SLIDE_LIBRARY = {
    "science": [
        (
            "Le cerveau humain",
            [
                "Poids : 1,4 kg (environ 2 % du poids corporel)",
                "Contient environ 86 milliards de neurones",
                "Utilise 20 % de l'énergie totale du corps",
                "Génère environ 23 watts de puissance électrique",
                "Vitesse de traitement : jusqu'à 120 m/s",
                "Capacité de stockage estimée à 2,5 pétaoctets",
            ],
            [
                ("Combien de neurones contient le cerveau ?",
                 ["12 milliards", "86 milliards", "100 milliards", "45 milliards"], 1),
                ("Quel pourcentage d'énergie le cerveau utilise-t-il ?",
                 ["10 %", "15 %", "20 %", "30 %"], 2),
                ("Quelle est la capacité de stockage estimée ?",
                 ["1,5 Po", "2,5 Po", "5 Po", "500 To"], 1),
            ],
        ),
        (
            "Exploration de Mars",
            [
                "Distance de la Terre : 54,6 à 401 millions de km",
                "Température de surface : −87 °C à −5 °C en moyenne",
                "Olympus Mons : plus haut volcan à 21,9 km",
                "Durée du jour (sol) : 24 heures 37 minutes",
                "Atmosphère : 95,3 % de dioxyde de carbone",
                "Gravité : 3,72 m/s² (38 % de celle de la Terre)",
            ],
            [
                ("Quelle est la hauteur d'Olympus Mons ?",
                 ["15,2 km", "18,6 km", "21,9 km", "25,1 km"], 2),
                ("Quel pourcentage de l'atmosphère de Mars est du CO₂ ?",
                 ["78,1 %", "89,7 %", "95,3 %", "99,2 %"], 2),
                ("Quelle est la gravité de Mars par rapport à la Terre ?",
                 ["28 %", "38 %", "48 %", "58 %"], 1),
            ],
        ),
        (
            "Faits sur les océans",
            [
                "Les océans couvrent 71 % de la surface terrestre",
                "Profondeur moyenne : 3 688 mètres",
                "Point le plus profond : fosse des Mariannes à 10 994 m",
                "Contient 97 % de l'eau de la Terre",
                "Océan Pacifique : le plus grand avec 165,25 millions de km²",
                "Température de l'eau : −2 °C à 36 °C",
            ],
            [
                ("Quelle est la profondeur moyenne des océans ?",
                 ["2 450 m", "3 688 m", "4 200 m", "5 100 m"], 1),
                ("Quel pourcentage de l'eau terrestre est dans les océans ?",
                 ["87 %", "92 %", "97 %", "99 %"], 2),
                ("Quelle est la profondeur de la fosse des Mariannes ?",
                 ["8 848 m", "9 500 m", "10 994 m", "12 100 m"], 2),
            ],
        ),
        (
            "La vitesse de la lumière",
            [
                "Vitesse dans le vide : 299 792 458 m/s",
                "La lumière parcourt 9 461 milliards de km par an",
                "La lumière du Soleil atteint la Terre en 8 min 20 s",
                "Lumière de la Lune : 1,3 seconde jusqu'à la Terre",
                "Étoile la plus proche (Proxima Centauri) : 4,24 années-lumière",
                "La lumière ralentit à 225 000 km/s dans l'eau",
            ],
            [
                ("Combien de temps met la lumière du Soleil pour atteindre la Terre ?",
                 ["4 min 10 s", "6 min 45 s", "8 min 20 s", "12 min 5 s"], 2),
                ("À quelle distance est Proxima Centauri en années-lumière ?",
                 ["2,18", "4,24", "6,71", "8,60"], 1),
                ("Quelle est la vitesse de la lumière dans l'eau ?",
                 ["150 000 km/s", "225 000 km/s", "275 000 km/s", "299 792 km/s"], 1),
            ],
        ),
        (
            "ADN et génétique",
            [
                "Génome humain : 3,2 milliards de paires de bases",
                "Les humains partagent 98,7 % de leur ADN avec les chimpanzés",
                "Chaque cellule contient environ 2 mètres d'ADN",
                "Seulement 1,5 % de l'ADN code pour des protéines",
                "23 paires de chromosomes dans les cellules humaines",
                "Vitesse de réplication de l'ADN : 1 000 nucléotides/seconde",
            ],
            [
                ("Combien de paires de bases dans le génome humain ?",
                 ["1,8 milliard", "3,2 milliards", "4,6 milliards", "6,4 milliards"], 1),
                ("Quel pourcentage de l'ADN code pour des protéines ?",
                 ["1,5 %", "5 %", "10 %", "25 %"], 0),
                ("Quelle longueur d'ADN contient chaque cellule ?",
                 ["0,5 mètre", "2 mètres", "5 mètres", "10 mètres"], 1),
            ],
        ),
    ],
    "business": [
        (
            "Marché mondial du café 2024",
            [
                "Valeur du marché : 495,2 milliards de dollars",
                "Consommation annuelle : 10,5 milliards de kg dans le monde",
                "Premier producteur : Brésil (37,4 % de la production mondiale)",
                "Prix moyen par kg : 14,80 $ (arabica)",
                "Segment café de spécialité en croissance de 12,3 % TCAC",
                "La Finlande mène la consommation par habitant : 12 kg/an",
            ],
            [
                ("Quelle est la valeur du marché mondial du café ?",
                 ["312,8 Mds $", "495,2 Mds $", "620,5 Mds $", "780,1 Mds $"], 1),
                ("Quel pourcentage du café mondial le Brésil produit-il ?",
                 ["22,1 %", "29,8 %", "37,4 %", "45,6 %"], 2),
                ("Quel pays mène la consommation de café par habitant ?",
                 ["Italie", "Colombie", "Finlande", "États-Unis"], 2),
            ],
        ),
        (
            "Ventes de véhicules électriques",
            [
                "Ventes mondiales de VE 2024 : 17,1 millions d'unités",
                "Part de marché : 22 % de toutes les ventes de voitures neuves",
                "La Chine mène avec 59 % des ventes mondiales de VE",
                "Coût moyen des batteries VE : 139 $/kWh",
                "Part de marché Tesla : 18,4 % des VE mondiaux",
                "Autonomie moyenne des VE : 348 km par charge",
            ],
            [
                ("Combien de VE ont été vendus dans le monde en 2024 ?",
                 ["9,8 millions", "13,5 millions", "17,1 millions", "21,4 millions"], 2),
                ("Quelle est la part de la Chine dans les ventes mondiales de VE ?",
                 ["35 %", "47 %", "59 %", "72 %"], 2),
                ("Quel est le coût moyen des batteries VE par kWh ?",
                 ["89 $", "139 $", "189 $", "239 $"], 1),
            ],
        ),
        (
            "Statistiques du télétravail",
            [
                "32,6 millions d'Américains travailleront à distance en 2025",
                "Augmentation de productivité : 13 % pour les télétravailleurs",
                "Temps de trajet économisé : 72 minutes/jour",
                "Les entreprises économisent 11 000 $ par télétravailleur/an",
                "67 % rapportent un meilleur équilibre vie pro/perso",
                "Marché de la visioconférence : 13,8 milliards de dollars",
            ],
            [
                ("Combien de temps de trajet les télétravailleurs économisent-ils ?",
                 ["45 minutes", "72 minutes", "90 minutes", "120 minutes"], 1),
                ("Combien les entreprises économisent-elles par télétravailleur ?",
                 ["5 000 $", "8 500 $", "11 000 $", "15 000 $"], 2),
                ("Quelle est l'augmentation de productivité en télétravail ?",
                 ["8 %", "13 %", "18 %", "25 %"], 1),
            ],
        ),
        (
            "Marché des smartphones T4 2024",
            [
                "Expéditions mondiales : 328,2 millions d'unités",
                "Samsung : 19,4 % de part de marché (n°1)",
                "Apple : 18,2 % de part de marché (n°2)",
                "Prix de vente moyen : 322 $",
                "Téléphones 5G : 78 % de toutes les expéditions",
                "Téléphones pliables : croissance de 49 % sur un an",
            ],
            [
                ("Combien de smartphones expédiés au T4 2024 ?",
                 ["245,6 millions", "328,2 millions", "412,7 millions", "501,3 millions"], 1),
                ("Quelle était la part de marché de Samsung ?",
                 ["15,8 %", "19,4 %", "23,1 %", "27,6 %"], 1),
                ("Quel pourcentage des expéditions étaient des téléphones 5G ?",
                 ["58 %", "68 %", "78 %", "88 %"], 2),
            ],
        ),
        (
            "Tourisme mondial 2024",
            [
                "Arrivées internationales : 1,4 milliard",
                "Recettes touristiques : 1 900 milliards de dollars",
                "Pays le plus visité : France (100 millions de visiteurs)",
                "Dépenses moyennes par touriste : 1 350 $",
                "Le tourisme emploie 330 millions de personnes dans le monde",
                "Croissance Asie-Pacifique : 18 % sur un an",
            ],
            [
                ("Combien d'arrivées touristiques internationales en 2024 ?",
                 ["0,8 milliard", "1,1 milliard", "1,4 milliard", "1,8 milliard"], 2),
                ("Quel pays a reçu le plus de visiteurs ?",
                 ["Espagne", "États-Unis", "France", "Italie"], 2),
                ("Combien de personnes le tourisme emploie-t-il dans le monde ?",
                 ["180 millions", "250 millions", "330 millions", "420 millions"], 2),
            ],
        ),
    ],
    "geography": [
        (
            "Le Japon",
            [
                "Population : 123,3 millions (2024)",
                "Capitale : Tokyo (13,96 millions d'habitants)",
                "Superficie : 377 975 km²",
                "Point culminant : Mont Fuji à 3 776 mètres",
                "PIB par habitant : 33 950 $",
                "Espérance de vie : 84,8 ans (la plus élevée au monde)",
            ],
            [
                ("Quelle est la population du Japon ?",
                 ["98,5 millions", "123,3 millions", "145,7 millions", "168,2 millions"], 1),
                ("Quelle est la hauteur du Mont Fuji ?",
                 ["2 954 m", "3 776 m", "4 421 m", "5 108 m"], 1),
                ("Quelle est l'espérance de vie au Japon ?",
                 ["78,2 ans", "81,5 ans", "84,8 ans", "87,3 ans"], 2),
            ],
        ),
        (
            "Le Brésil",
            [
                "Population : 216,4 millions (2024)",
                "Capitale : Brasília (pas São Paulo ni Rio)",
                "Superficie : 8 515 767 km² (5e plus grand pays)",
                "Forêt amazonienne : 5,5 millions de km²",
                "Langue officielle : portugais",
                "Littoral : 7 491 km de long",
            ],
            [
                ("Quelle est la capitale du Brésil ?",
                 ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador"], 2),
                ("Quelle est la superficie de la forêt amazonienne ?",
                 ["3,2 M km²", "5,5 M km²", "7,8 M km²", "9,1 M km²"], 1),
                ("Quelle est la longueur du littoral brésilien ?",
                 ["4 230 km", "5 860 km", "7 491 km", "9 120 km"], 2),
            ],
        ),
        (
            "L'Australie",
            [
                "Population : 26,6 millions (2024)",
                "Capitale : Canberra (pas Sydney)",
                "Superficie : 7 692 024 km² (6e plus grand pays)",
                "Grande Barrière de corail : 2 300 km de long",
                "Point culminant : Mont Kosciuszko à 2 228 m",
                "87 % de la population vit en zone urbaine",
            ],
            [
                ("Quelle est la population de l'Australie ?",
                 ["18,4 millions", "26,6 millions", "34,2 millions", "42,8 millions"], 1),
                ("Quelle est la longueur de la Grande Barrière de corail ?",
                 ["1 200 km", "1 800 km", "2 300 km", "2 900 km"], 2),
                ("Quel pourcentage d'Australiens vit en zone urbaine ?",
                 ["72 %", "79 %", "87 %", "94 %"], 2),
            ],
        ),
        (
            "La Suisse",
            [
                "Population : 8,9 millions (2024)",
                "Capitale : Berne (pas Zurich ni Genève)",
                "4 langues officielles : allemand, français, italien, romanche",
                "Superficie : 41 285 km²",
                "Point culminant : Pointe Dufour à 4 634 m",
                "PIB par habitant : 99 994 $ (2e mondial)",
            ],
            [
                ("Quelle est la capitale de la Suisse ?",
                 ["Zurich", "Genève", "Berne", "Bâle"], 2),
                ("Combien de langues officielles a la Suisse ?",
                 ["2", "3", "4", "5"], 2),
                ("Quel est le PIB par habitant de la Suisse ?",
                 ["67 450 $", "82 310 $", "99 994 $", "115 200 $"], 2),
            ],
        ),
        (
            "L'Égypte",
            [
                "Population : 109,3 millions (2024)",
                "Capitale : Le Caire (21,9 millions d'habitants)",
                "Le Nil : 6 650 km (plus long fleuve d'Afrique)",
                "Grande Pyramide : 146,6 mètres de haut (à l'origine)",
                "Superficie : 1 002 450 km² (97 % de désert)",
                "Canal de Suez : 193,3 km de long, ouvert en 1869",
            ],
            [
                ("Quelle est la population du Caire ?",
                 ["14,2 millions", "17,5 millions", "21,9 millions", "25,3 millions"], 2),
                ("Quelle est la longueur du Nil ?",
                 ["4 130 km", "5 390 km", "6 650 km", "7 920 km"], 2),
                ("Quelle est la longueur du canal de Suez ?",
                 ["120,5 km", "156,8 km", "193,3 km", "231,7 km"], 2),
            ],
        ),
    ],
    "motivation": [
        (
            "La règle des 10 000 heures",
            [
                "Popularisée par Malcolm Gladwell dans Outliers (2008)",
                "Basée sur les recherches de K. Anders Ericsson",
                "Les violonistes d'élite avaient 10 000 heures de pratique à 20 ans",
                "La pratique délibérée compte plus que le total d'heures",
                "Les meilleurs pratiquent 4 heures/jour avec concentration totale",
                "Les boucles de rétroaction accélèrent l'apprentissage de 26 %",
            ],
            [
                ("Qui a popularisé la règle des 10 000 heures ?",
                 ["Daniel Kahneman", "Malcolm Gladwell", "Cal Newport", "James Clear"], 1),
                ("Combien d'heures/jour les meilleurs pratiquent-ils ?",
                 ["2 heures", "4 heures", "6 heures", "8 heures"], 1),
                ("De combien les boucles de rétroaction accélèrent-elles l'apprentissage ?",
                 ["12 %", "18 %", "26 %", "35 %"], 2),
            ],
        ),
        (
            "Recherche sur l'état d'esprit de croissance",
            [
                "Inventé par Carol Dweck à l'Université Stanford",
                "Les élèves félicités pour l'effort se sont améliorés de 30 % de plus",
                "État d'esprit fixe : l'intelligence est statique",
                "État d'esprit de croissance : les capacités se développent par la pratique",
                "73 % des PDG de premier plan s'identifient comme ayant un état d'esprit de croissance",
                "Les interventions sur l'état d'esprit ont augmenté les moyennes de 0,3 point",
            ],
            [
                ("Qui a inventé le terme 'état d'esprit de croissance' ?",
                 ["Angela Duckworth", "Carol Dweck", "Martin Seligman", "Amy Cuddy"], 1),
                ("De combien les élèves félicités pour l'effort se sont-ils améliorés ?",
                 ["10 %", "20 %", "30 %", "40 %"], 2),
                ("Quel pourcentage des PDG ont un état d'esprit de croissance ?",
                 ["53 %", "63 %", "73 %", "83 %"], 2),
            ],
        ),
        (
            "Le pouvoir des habitudes",
            [
                "40 % des actions quotidiennes sont des habitudes",
                "Boucle d'habitude : signal → routine → récompense (Duhigg)",
                "Formation d'une nouvelle habitude : 66 jours en moyenne",
                "Les intentions de mise en œuvre augmentent le taux de réussite de 91 %",
                "Les habitudes clés déclenchent des changements positifs en cascade",
                "Empilement d'habitudes : rattacher les nouvelles aux existantes",
            ],
            [
                ("Quel pourcentage des actions quotidiennes sont des habitudes ?",
                 ["20 %", "30 %", "40 %", "50 %"], 2),
                ("Combien de jours faut-il pour former une nouvelle habitude ?",
                 ["21 jours", "45 jours", "66 jours", "90 jours"], 2),
                ("De combien les intentions de mise en œuvre augmentent-elles le succès ?",
                 ["51 %", "71 %", "81 %", "91 %"], 3),
            ],
        ),
        (
            "L'état de flow et la performance",
            [
                "Concept développé par Mihaly Csikszentmihalyi en 1975",
                "Le flow augmente la productivité jusqu'à 500 %",
                "Nécessite un équilibre défi-compétence (4 % au-dessus du niveau actuel)",
                "Temps moyen pour entrer en flow : 15–20 minutes",
                "Les interruptions réinitialisent complètement le minuteur de flow",
                "Le flow déclenche 5 neurochimiques : dopamine, noradrénaline, endorphines, anandamide, sérotonine",
            ],
            [
                ("Qui a développé le concept de flow ?",
                 ["Daniel Pink", "Mihaly Csikszentmihalyi", "Cal Newport", "Adam Grant"], 1),
                ("De combien le flow peut-il augmenter la productivité ?",
                 ["100 %", "200 %", "350 %", "500 %"], 3),
                ("Combien de temps faut-il pour entrer en flow ?",
                 ["5–10 minutes", "15–20 minutes", "25–30 minutes", "35–40 minutes"], 1),
            ],
        ),
        (
            "Ténacité et persévérance",
            [
                "Recherche d'Angela Duckworth à l'UPenn",
                "La ténacité prédit mieux le succès que le QI dans 78 % des études",
                "Cadets de West Point : le score de ténacité prédisait le taux de réussite",
                "Ténacité = passion + persévérance soutenue sur des années",
                "Les personnes tenaces pratiquent 32 % d'heures de plus par semaine",
                "La ténacité peut être développée — elle n'est pas purement innée",
            ],
            [
                ("Qui a étudié la ténacité ?",
                 ["Carol Dweck", "Angela Duckworth", "Martin Seligman", "Dan Pink"], 1),
                ("Dans quel pourcentage des études la ténacité surpasse-t-elle le QI ?",
                 ["58 %", "68 %", "78 %", "88 %"], 2),
                ("Combien de plus les personnes tenaces pratiquent-elles par semaine ?",
                 ["12 %", "22 %", "32 %", "42 %"], 2),
            ],
        ),
    ],
    "neuroplasticity": [
        (
            "Bases de la neuroplasticité",
            [
                "Le cerveau forme 1 million de nouvelles connexions/seconde chez le nourrisson",
                "Les adultes génèrent ~700 nouveaux neurones/jour dans l'hippocampe",
                "Les chauffeurs de taxi londoniens ont un hippocampe postérieur 16 % plus grand",
                "La neuroplasticité culmine avant 25 ans mais continue toute la vie",
                "Apprendre une nouvelle compétence augmente la matière grise en 2 semaines",
                "Le sommeil consolide les voies neuronales — 7–9 heures optimal",
            ],
            [
                ("Combien de nouveaux neurones les adultes génèrent-ils par jour ?",
                 ["200", "500", "700", "1 000"], 2),
                ("De combien l'hippocampe des chauffeurs de taxi est-il plus grand ?",
                 ["8 %", "12 %", "16 %", "22 %"], 2),
                ("En combien de temps l'apprentissage augmente-t-il la matière grise ?",
                 ["2 jours", "2 semaines", "2 mois", "6 mois"], 1),
            ],
        ),
        (
            "Formation de la mémoire",
            [
                "La mémoire à court terme dure 15–30 secondes sans répétition",
                "Capacité de la mémoire de travail : 4 ± 1 éléments",
                "Consolidation : l'hippocampe transfère au néocortex pendant le sommeil",
                "La répétition espacée améliore la rétention de 200 %",
                "Les souvenirs émotionnels sont 3× plus forts (implication de l'amygdale)",
                "La technique du palais de la mémoire améliore le rappel de 80 %",
            ],
            [
                ("Combien de temps dure la mémoire à court terme sans répétition ?",
                 ["5–10 s", "15–30 s", "45–60 s", "2–3 min"], 1),
                ("De combien la répétition espacée améliore-t-elle la rétention ?",
                 ["50 %", "100 %", "200 %", "300 %"], 2),
                ("De combien le palais de la mémoire améliore-t-il le rappel ?",
                 ["40 %", "60 %", "80 %", "100 %"], 2),
            ],
        ),
        (
            "Exercice et cerveau",
            [
                "30 min d'aérobie augmentent le BDNF de 32 %",
                "L'exercice régulier agrandit l'hippocampe de 2 %",
                "L'exercice améliore les fonctions exécutives de 20 %",
                "Bénéfices cognitifs optimaux : 150 min d'exercice modéré/semaine",
                "L'exercice après l'apprentissage améliore la rétention de 10 %",
                "La forme physique réduit le risque de démence de 30 %",
            ],
            [
                ("De combien 30 min d'aérobie augmentent-elles le BDNF ?",
                 ["12 %", "22 %", "32 %", "42 %"], 2),
                ("De combien l'exercice agrandit-il l'hippocampe ?",
                 ["0,5 %", "1 %", "2 %", "4 %"], 2),
                ("Combien de minutes d'exercice modéré par semaine sont optimales ?",
                 ["60 min", "90 min", "150 min", "200 min"], 2),
            ],
        ),
        (
            "Méditation et changements neuronaux",
            [
                "8 semaines de méditation augmentent la densité de matière grise",
                "Les méditants montrent 25 % plus d'activité dans le cortex préfrontal",
                "La pleine conscience réduit le volume de l'amygdale de 5 %",
                "Méditants de longue date : 50 % plus d'activité d'ondes gamma",
                "La méditation améliore la durée d'attention de 14 %",
                "12 min de pratique quotidienne montrent des changements cérébraux mesurables",
            ],
            [
                ("Combien de plus d'activité préfrontale les méditants montrent-ils ?",
                 ["10 %", "15 %", "25 %", "35 %"], 2),
                ("De combien la pleine conscience réduit-elle le volume de l'amygdale ?",
                 ["2 %", "5 %", "8 %", "12 %"], 1),
                ("Combien de minutes de méditation quotidienne montrent des effets mesurables ?",
                 ["5 min", "8 min", "12 min", "20 min"], 2),
            ],
        ),
        (
            "Bilinguisme et cognition",
            [
                "Les bilingues changent de tâche 4,5 fois plus vite",
                "L'apparition de la démence est retardée de 4–5 ans chez les bilingues",
                "Les cerveaux bilingues ont une matière grise plus dense dans le CCA",
                "Contrôle exécutif : 15 % meilleur chez les bilingues",
                "Période critique pour l'acquisition du langage : avant 7 ans",
                "Les bilingues montrent une capacité de mémoire de travail supérieure",
            ],
            [
                ("Combien de fois plus vite les bilingues changent-ils de tâche ?",
                 ["2,5×", "3,5×", "4,5×", "5,5×"], 2),
                ("De combien d'années le bilinguisme retarde-t-il la démence ?",
                 ["1–2 ans", "2–3 ans", "4–5 ans", "6–7 ans"], 2),
                ("Jusqu'à quel âge dure la période critique pour les langues ?",
                 ["5 ans", "7 ans", "10 ans", "12 ans"], 1),
            ],
        ),
    ],
    "humor": [
        (
            "La science du rire",
            [
                "Un adulte moyen rit 17 fois par jour",
                "Le rire brûle 10–40 calories en 15 minutes",
                "Les bébés commencent à rire vers 4 mois",
                "Le rire libère des endorphines et réduit le cortisol de 39 %",
                "Gélotologie : l'étude scientifique du rire",
                "Le rire est contagieux — 30× plus probable en groupe",
            ],
            [
                ("Combien de fois un adulte rit-il en moyenne par jour ?",
                 ["7 fois", "12 fois", "17 fois", "25 fois"], 2),
                ("De combien le rire réduit-il le cortisol ?",
                 ["19 %", "29 %", "39 %", "49 %"], 2),
                ("Comment s'appelle la science du rire ?",
                 ["Humorologie", "Gélotologie", "Risologie", "Comicologie"], 1),
            ],
        ),
        (
            "Faits animaux étranges",
            [
                "Les pieuvres ont 3 cœurs et du sang bleu",
                "Un colibri pèse moins qu'une pièce de 5 centimes",
                "Les vaches ont des meilleures amies et sont stressées sans elles",
                "Les dauphins dorment avec un œil ouvert",
                "Les flamants roses ne sont roses qu'à cause de leur régime de crevettes",
                "Les paresseux mettent 2 semaines à digérer leur nourriture",
            ],
            [
                ("Combien de cœurs a une pieuvre ?",
                 ["1", "2", "3", "4"], 2),
                ("Pourquoi les flamants roses sont-ils roses ?",
                 ["Génétique", "Lumière du soleil", "Régime de crevettes", "Chimie de l'eau"], 2),
                ("Combien de temps les paresseux mettent-ils à digérer ?",
                 ["3 jours", "1 semaine", "2 semaines", "1 mois"], 2),
            ],
        ),
        (
            "Records du monde absurdes",
            [
                "Plus long hoquet : 68 ans (Charles Osborne)",
                "Plus de t-shirts portés en même temps : 260",
                "Course à reculons la plus rapide : 100 m en 13,6 secondes",
                "Plus long ongle jamais mesuré : 8,65 mètres",
                "Plus de hot-dogs mangés en 10 min : 76",
                "Ronflement le plus fort mesuré : 93 décibels",
            ],
            [
                ("Combien de temps a duré le plus long hoquet ?",
                 ["12 ans", "34 ans", "68 ans", "85 ans"], 2),
                ("Combien de t-shirts portés en même temps ?",
                 ["120", "185", "260", "340"], 2),
                ("Quel était le ronflement le plus fort mesuré ?",
                 ["73 dB", "83 dB", "93 dB", "103 dB"], 2),
            ],
        ),
        (
            "Curiosités alimentaires",
            [
                "Le miel ne se périme jamais — du miel de 3 000 ans était encore comestible",
                "Les bananes sont botaniquement des baies, pas les fraises",
                "Le ketchup était vendu comme médicament dans les années 1830",
                "Un humain moyen mange 35 tonnes de nourriture dans sa vie",
                "Le wasabi au restaurant est généralement du raifort coloré",
                "Un ananas met 2–3 ans à pousser",
            ],
            [
                ("Quel âge avait le plus vieux miel encore comestible ?",
                 ["500 ans", "1 000 ans", "3 000 ans", "5 000 ans"], 2),
                ("Combien de nourriture un humain mange-t-il dans sa vie ?",
                 ["15 tonnes", "25 tonnes", "35 tonnes", "50 tonnes"], 2),
                ("Combien de temps met un ananas à pousser ?",
                 ["6 mois", "1 an", "2–3 ans", "5 ans"], 2),
            ],
        ),
        (
            "Inutile mais vrai",
            [
                "Un éclair est 5× plus chaud que la surface du Soleil",
                "La Terre tourne à 1 670 km/h à l'équateur",
                "Les os humains sont plus solides que l'acier (à poids égal)",
                "Il y a plus d'étoiles dans l'univers que de grains de sable sur Terre",
                "Votre estomac renouvelle sa muqueuse tous les 3–4 jours",
                "L'Université d'Oxford est plus ancienne que l'Empire aztèque",
            ],
            [
                ("Combien de fois un éclair est-il plus chaud que le Soleil ?",
                 ["2×", "3×", "5×", "8×"], 2),
                ("À quelle vitesse la Terre tourne-t-elle à l'équateur ?",
                 ["670 km/h", "1 070 km/h", "1 670 km/h", "2 270 km/h"], 2),
                ("À quelle fréquence la muqueuse de l'estomac se renouvelle-t-elle ?",
                 ["Tous les 1–2 jours", "Tous les 3–4 jours", "Tous les 7 jours", "Tous les 14 jours"], 1),
            ],
        ),
    ],
    "history": [
        (
            "La Rome antique",
            [
                "Fondation : 753 av. J.-C. (selon la légende)",
                "Population maximale : 1 million (1er siècle apr. J.-C.)",
                "Réseau routier : 400 000 km dans tout l'empire",
                "Le Colisée accueillait 50 000–80 000 spectateurs",
                "Les aqueducs transportaient 1 million de m³ d'eau par jour",
                "L'Empire a duré plus de 1 000 ans (753 av. J.-C. – 476 apr. J.-C.)",
            ],
            [
                ("Quand Rome a-t-elle été fondée selon la légende ?",
                 ["509 av. J.-C.", "753 av. J.-C.", "264 av. J.-C.", "1 000 av. J.-C."], 1),
                ("Combien de spectateurs le Colisée accueillait-il ?",
                 ["20 000–30 000", "35 000–45 000", "50 000–80 000", "90 000–100 000"], 2),
                ("Quelle était la longueur du réseau routier romain ?",
                 ["100 000 km", "250 000 km", "400 000 km", "600 000 km"], 2),
            ],
        ),
        (
            "L'alunissage",
            [
                "Date : 20 juillet 1969 (Apollo 11)",
                "Premiers mots sur la Lune : Neil Armstrong",
                "Durée de la mission : 8 jours 3 heures 18 minutes",
                "Distance Terre–Lune : 384 400 km",
                "Roches lunaires rapportées : 21,55 kg",
                "Coût estimé : 25,4 milliards $ (dollars de 1973)",
            ],
            [
                ("Quand a eu lieu le premier alunissage ?",
                 ["15 mars 1968", "20 juillet 1969", "12 avril 1970", "3 juin 1971"], 1),
                ("Combien de roches lunaires ont été rapportées ?",
                 ["8,2 kg", "15,3 kg", "21,55 kg", "34,7 kg"], 2),
                ("Quelle est la distance Terre–Lune ?",
                 ["284 400 km", "384 400 km", "484 400 km", "584 400 km"], 1),
            ],
        ),
        (
            "Seconde Guerre mondiale — Chiffres clés",
            [
                "Durée : 1939–1945 (6 ans)",
                "Nations impliquées : plus de 30",
                "Victimes totales estimées : 70–85 millions",
                "Jour J : 6 juin 1944 — 156 000 soldats alliés",
                "Coût : estimé à 1 657 milliards $ (dollars de 1945)",
                "Fin en Europe : 8 mai 1945 (Jour de la Victoire)",
            ],
            [
                ("Combien de nations étaient impliquées dans la 2e Guerre mondiale ?",
                 ["Plus de 10", "Plus de 20", "Plus de 30", "Plus de 50"], 2),
                ("Combien de soldats alliés ont débarqué le Jour J ?",
                 ["75 000", "120 000", "156 000", "200 000"], 2),
                ("Quand la guerre a-t-elle pris fin en Europe ?",
                 ["8 mai 1945", "2 septembre 1945", "15 août 1945", "11 novembre 1944"], 0),
            ],
        ),
        (
            "La Renaissance",
            [
                "Période : environ 1350–1600 apr. J.-C.",
                "Origine : Florence, Italie",
                "Léonard de Vinci a peint la Joconde vers 1503–1519",
                "L'imprimerie de Gutenberg : vers 1440",
                "Le plafond de la Chapelle Sixtine par Michel-Ange : 1508–1512",
                "Population européenne : ~60 millions après la peste",
            ],
            [
                ("Où la Renaissance a-t-elle commencé ?",
                 ["Paris", "Rome", "Florence", "Venise"], 2),
                ("Quand Gutenberg a-t-il inventé l'imprimerie ?",
                 ["vers 1380", "vers 1440", "vers 1500", "vers 1550"], 1),
                ("Combien de temps Michel-Ange a-t-il peint le plafond de la Sixtine ?",
                 ["1 an", "2 ans", "4 ans", "8 ans"], 2),
            ],
        ),
        (
            "La Révolution industrielle",
            [
                "Début : vers 1760 en Grande-Bretagne",
                "Machine à vapeur de Watt : brevetée en 1769",
                "Premier chemin de fer : Stockton–Darlington en 1825",
                "Population urbaine passée de 20 % à 50 % en 1850",
                "Travail des enfants : dès 5 ans, journées de 16 heures",
                "Production de coton augmentée de 800 % entre 1770 et 1800",
            ],
            [
                ("Où la Révolution industrielle a-t-elle commencé ?",
                 ["France", "Allemagne", "Grande-Bretagne", "États-Unis"], 2),
                ("Quand la machine à vapeur de Watt a-t-elle été brevetée ?",
                 ["1745", "1769", "1785", "1801"], 1),
                ("De combien la production de coton a-t-elle augmenté 1770–1800 ?",
                 ["200 %", "400 %", "800 %", "1 200 %"], 2),
            ],
        ),
    ],
    "nutrition": [
        (
            "Macronutriments",
            [
                "Glucides : 4 calories par gramme",
                "Protéines : 4 calories par gramme",
                "Lipides : 9 calories par gramme",
                "Répartition recommandée : 45–65 % glucides, 20–35 % lipides, 10–35 % protéines",
                "Fibres : 25–30 g par jour recommandés",
                "Un adulte moyen a besoin de 2 000–2 500 kcal/jour",
            ],
            [
                ("Combien de calories contient un gramme de lipides ?",
                 ["4", "7", "9", "12"], 2),
                ("Combien de fibres par jour sont recommandées ?",
                 ["10–15 g", "15–20 g", "25–30 g", "35–40 g"], 2),
                ("Quel pourcentage des calories devrait provenir des glucides ?",
                 ["25–40 %", "45–65 %", "60–80 %", "70–90 %"], 1),
            ],
        ),
        (
            "Faits sur l'hydratation",
            [
                "Corps humain : 60 % d'eau",
                "Cerveau et cœur : 73 % d'eau",
                "Apport recommandé : 2,7–3,7 litres/jour (nourriture incluse)",
                "2 % de déshydratation réduit la performance cognitive de 25 %",
                "Les reins filtrent 180 litres de sang par jour",
                "La caféine est un diurétique léger — l'effet net est minimal",
            ],
            [
                ("Quel pourcentage du corps est constitué d'eau ?",
                 ["45 %", "52 %", "60 %", "70 %"], 2),
                ("De combien 2 % de déshydratation réduit-elle la performance cognitive ?",
                 ["10 %", "15 %", "25 %", "35 %"], 2),
                ("Combien de litres de sang les reins filtrent-ils par jour ?",
                 ["90 litres", "120 litres", "180 litres", "240 litres"], 2),
            ],
        ),
        (
            "Vitamines et minéraux",
            [
                "Vitamine D : 1 milliard de personnes dans le monde sont carencées",
                "Fer : 25 % de la population mondiale souffre de carence en fer",
                "Vitamine C : 90 mg/jour recommandés pour les adultes",
                "Calcium : 99 % est stocké dans les os et les dents",
                "B12 : naturellement présente uniquement dans les produits animaux",
                "Zinc : soutient plus de 300 réactions enzymatiques",
            ],
            [
                ("Combien de personnes sont carencées en vitamine D dans le monde ?",
                 ["100 millions", "500 millions", "1 milliard", "2 milliards"], 2),
                ("Combien de vitamine C par jour est recommandé ?",
                 ["45 mg", "60 mg", "90 mg", "120 mg"], 2),
                ("Quel pourcentage du calcium est dans les os et les dents ?",
                 ["85 %", "92 %", "99 %", "100 %"], 2),
            ],
        ),
        (
            "Connexion intestin-cerveau",
            [
                "L'intestin contient 500 millions de neurones",
                "95 % de la sérotonine est produite dans l'intestin",
                "Microbiome intestinal : 100 000 milliards de bactéries",
                "Nerf vague : connexion directe entre intestin et cerveau",
                "La santé intestinale influence l'humeur, le sommeil et la cognition",
                "Les probiotiques peuvent réduire les symptômes d'anxiété de 20 %",
            ],
            [
                ("Combien de neurones l'intestin contient-il ?",
                 ["100 millions", "300 millions", "500 millions", "800 millions"], 2),
                ("Quel pourcentage de la sérotonine est produit dans l'intestin ?",
                 ["50 %", "75 %", "85 %", "95 %"], 3),
                ("De combien les probiotiques peuvent-ils réduire l'anxiété ?",
                 ["10 %", "15 %", "20 %", "30 %"], 2),
            ],
        ),
        (
            "Caféine et performance",
            [
                "La caféine bloque les récepteurs d'adénosine dans le cerveau",
                "Début d'action : 15–45 minutes après ingestion",
                "Demi-vie : 5–6 heures en moyenne",
                "Dose optimale : 3–6 mg/kg de poids corporel",
                "Améliore le temps de réaction de 11 %",
                "Dose quotidienne sûre : jusqu'à 400 mg (environ 4 tasses de café)",
            ],
            [
                ("Combien de temps faut-il pour que la caféine agisse ?",
                 ["5–10 min", "15–45 min", "60–90 min", "2–3 heures"], 1),
                ("De combien la caféine améliore-t-elle le temps de réaction ?",
                 ["5 %", "8 %", "11 %", "15 %"], 2),
                ("Quelle quantité de caféine par jour est considérée comme sûre ?",
                 ["200 mg", "300 mg", "400 mg", "500 mg"], 2),
            ],
        ),
    ],
}
