"""Portuguese slide library for Slide Processing exercise."""

SLIDE_LIBRARY = {
    "science": [
        (
            "O cérebro humano",
            [
                "Peso: 1,4 kg (cerca de 2 % do peso corporal)",
                "Contém aproximadamente 86 mil milhões de neurónios",
                "Usa 20 % da energia total do corpo",
                "Gera cerca de 23 watts de potência elétrica",
                "Velocidade de processamento: até 120 m/s",
                "Capacidade de armazenamento estimada em 2,5 petabytes",
            ],
            [
                ("Quantos neurónios contém o cérebro?",
                 ["12 mil milhões", "86 mil milhões", "100 mil milhões", "45 mil milhões"], 1),
                ("Que percentagem de energia corporal usa o cérebro?",
                 ["10 %", "15 %", "20 %", "30 %"], 2),
                ("Qual é a capacidade de armazenamento estimada?",
                 ["1,5 petabytes", "2,5 petabytes", "5 petabytes", "500 terabytes"], 1),
            ],
        ),
        (
            "Exploração de Marte",
            [
                "Distância à Terra: 54,6 a 401 milhões de km",
                "Temperatura à superfície: −87 °C a −5 °C em média",
                "Olympus Mons: vulcão mais alto com 21,9 km",
                "Duração do dia (sol): 24 horas 37 minutos",
                "Atmosfera: 95,3 % de dióxido de carbono",
                "Gravidade: 3,72 m/s² (38 % da terrestre)",
            ],
            [
                ("Qual é a altura do Olympus Mons?",
                 ["15,2 km", "18,6 km", "21,9 km", "25,1 km"], 2),
                ("Que percentagem da atmosfera de Marte é CO₂?",
                 ["78,1 %", "89,7 %", "95,3 %", "99,2 %"], 2),
                ("Qual é a gravidade de Marte comparada com a Terra?",
                 ["28 %", "38 %", "48 %", "58 %"], 1),
            ],
        ),
        (
            "Factos sobre os oceanos",
            [
                "Os oceanos cobrem 71 % da superfície terrestre",
                "Profundidade média: 3.688 metros",
                "Ponto mais profundo: Fossa das Marianas com 10.994 m",
                "Contém 97 % da água da Terra",
                "Oceano Pacífico: o maior com 165,25 milhões de km²",
                "Temperatura da água: −2 °C a 36 °C",
            ],
            [
                ("Qual é a profundidade média dos oceanos?",
                 ["2.450 m", "3.688 m", "4.200 m", "5.100 m"], 1),
                ("Que percentagem da água terrestre está nos oceanos?",
                 ["87 %", "92 %", "97 %", "99 %"], 2),
                ("Qual é a profundidade da Fossa das Marianas?",
                 ["8.848 m", "9.500 m", "10.994 m", "12.100 m"], 2),
            ],
        ),
        (
            "A velocidade da luz",
            [
                "Velocidade no vácuo: 299.792.458 m/s",
                "A luz percorre 9,461 biliões de km por ano",
                "A luz solar chega à Terra em 8 min 20 s",
                "Luz da Lua: 1,3 segundos até à Terra",
                "Estrela mais próxima (Proxima Centauri): 4,24 anos-luz",
                "A luz abranda para 225.000 km/s na água",
            ],
            [
                ("Quanto tempo demora a luz solar a chegar à Terra?",
                 ["4 min 10 s", "6 min 45 s", "8 min 20 s", "12 min 5 s"], 2),
                ("A que distância está Proxima Centauri em anos-luz?",
                 ["2,18", "4,24", "6,71", "8,60"], 1),
                ("Qual é a velocidade da luz na água?",
                 ["150.000 km/s", "225.000 km/s", "275.000 km/s", "299.792 km/s"], 1),
            ],
        ),
        (
            "ADN e genética",
            [
                "Genoma humano: 3,2 mil milhões de pares de bases",
                "Os humanos partilham 98,7 % do ADN com os chimpanzés",
                "Cada célula contém cerca de 2 metros de ADN",
                "Apenas 1,5 % do ADN codifica proteínas",
                "23 pares de cromossomas nas células humanas",
                "Velocidade de replicação do ADN: 1.000 nucleótidos/segundo",
            ],
            [
                ("Quantos pares de bases tem o genoma humano?",
                 ["1,8 mil milhões", "3,2 mil milhões", "4,6 mil milhões", "6,4 mil milhões"], 1),
                ("Que percentagem do ADN codifica proteínas?",
                 ["1,5 %", "5 %", "10 %", "25 %"], 0),
                ("Quanto ADN contém cada célula?",
                 ["0,5 metros", "2 metros", "5 metros", "10 metros"], 1),
            ],
        ),
    ],
    "business": [
        (
            "Mercado global do café 2024",
            [
                "Valor de mercado: 495,2 mil milhões de dólares",
                "Consumo anual: 10,5 mil milhões de kg no mundo",
                "Maior produtor: Brasil (37,4 % da produção mundial)",
                "Preço médio por kg: 14,80 $ (arábica)",
                "Segmento de café especial cresce a 12,3 % CAGR",
                "A Finlândia lidera o consumo per capita: 12 kg/ano",
            ],
            [
                ("Qual é o valor do mercado global do café?",
                 ["312,8 Mrd $", "495,2 Mrd $", "620,5 Mrd $", "780,1 Mrd $"], 1),
                ("Que percentagem do café mundial o Brasil produz?",
                 ["22,1 %", "29,8 %", "37,4 %", "45,6 %"], 2),
                ("Que país lidera o consumo de café per capita?",
                 ["Itália", "Colômbia", "Finlândia", "EUA"], 2),
            ],
        ),
        (
            "Vendas de veículos elétricos",
            [
                "Vendas globais de VE 2024: 17,1 milhões de unidades",
                "Quota de mercado: 22 % de todas as vendas de carros novos",
                "A China lidera com 59 % das vendas globais de VE",
                "Custo médio da bateria VE: 139 $/kWh",
                "Quota de mercado da Tesla: 18,4 % dos VE globais",
                "Autonomia média dos VE: 348 km por carga",
            ],
            [
                ("Quantos VE foram vendidos no mundo em 2024?",
                 ["9,8 milhões", "13,5 milhões", "17,1 milhões", "21,4 milhões"], 2),
                ("Qual é a quota da China nas vendas globais de VE?",
                 ["35 %", "47 %", "59 %", "72 %"], 2),
                ("Qual é o custo médio da bateria VE por kWh?",
                 ["89 $", "139 $", "189 $", "239 $"], 1),
            ],
        ),
        (
            "Estatísticas do teletrabalho",
            [
                "32,6 milhões de americanos trabalharão remotamente em 2025",
                "Aumento de produtividade: 13 % para teletrabalhadores",
                "Tempo de deslocação poupado: 72 minutos/dia",
                "As empresas poupam 11.000 $ por teletrabalhador/ano",
                "67 % reportam melhor equilíbrio vida-trabalho",
                "Mercado de videoconferência: 13,8 mil milhões de dólares",
            ],
            [
                ("Quanto tempo de deslocação poupam os teletrabalhadores?",
                 ["45 minutos", "72 minutos", "90 minutos", "120 minutos"], 1),
                ("Quanto poupam as empresas por teletrabalhador?",
                 ["5.000 $", "8.500 $", "11.000 $", "15.000 $"], 2),
                ("Qual é o aumento de produtividade no teletrabalho?",
                 ["8 %", "13 %", "18 %", "25 %"], 1),
            ],
        ),
        (
            "Mercado de smartphones T4 2024",
            [
                "Expedições globais: 328,2 milhões de unidades",
                "Samsung: 19,4 % de quota de mercado (n.º 1)",
                "Apple: 18,2 % de quota de mercado (n.º 2)",
                "Preço médio de venda: 322 $",
                "Telefones 5G: 78 % de todas as expedições",
                "Telefones dobráveis cresceram 49 % em relação ao ano anterior",
            ],
            [
                ("Quantos smartphones foram expedidos no T4 2024?",
                 ["245,6 milhões", "328,2 milhões", "412,7 milhões", "501,3 milhões"], 1),
                ("Qual foi a quota de mercado da Samsung?",
                 ["15,8 %", "19,4 %", "23,1 %", "27,6 %"], 1),
                ("Que percentagem das expedições foram telefones 5G?",
                 ["58 %", "68 %", "78 %", "88 %"], 2),
            ],
        ),
        (
            "Turismo mundial 2024",
            [
                "Chegadas internacionais: 1,4 mil milhões",
                "Receitas turísticas: 1,9 biliões de dólares",
                "País mais visitado: França (100 milhões de visitantes)",
                "Gasto médio por turista: 1.350 $",
                "O turismo emprega 330 milhões de pessoas no mundo",
                "Crescimento Ásia-Pacífico: 18 % em relação ao ano anterior",
            ],
            [
                ("Quantas chegadas turísticas internacionais houve em 2024?",
                 ["0,8 mil milhões", "1,1 mil milhões", "1,4 mil milhões", "1,8 mil milhões"], 2),
                ("Que país teve mais visitantes?",
                 ["Espanha", "EUA", "França", "Itália"], 2),
                ("Quantas pessoas emprega o turismo no mundo?",
                 ["180 milhões", "250 milhões", "330 milhões", "420 milhões"], 2),
            ],
        ),
    ],
    "geography": [
        (
            "Japão",
            [
                "População: 123,3 milhões (2024)",
                "Capital: Tóquio (13,96 milhões de habitantes)",
                "Área: 377.975 km²",
                "Ponto mais alto: Monte Fuji com 3.776 metros",
                "PIB per capita: 33.950 $",
                "Esperança de vida: 84,8 anos (a mais alta do mundo)",
            ],
            [
                ("Qual é a população do Japão?",
                 ["98,5 milhões", "123,3 milhões", "145,7 milhões", "168,2 milhões"], 1),
                ("Qual é a altura do Monte Fuji?",
                 ["2.954 m", "3.776 m", "4.421 m", "5.108 m"], 1),
                ("Qual é a esperança de vida no Japão?",
                 ["78,2 anos", "81,5 anos", "84,8 anos", "87,3 anos"], 2),
            ],
        ),
        (
            "Brasil",
            [
                "População: 216,4 milhões (2024)",
                "Capital: Brasília (não São Paulo nem Rio)",
                "Área: 8.515.767 km² (5.º maior país)",
                "Floresta Amazónica: 5,5 milhões de km²",
                "Língua oficial: português",
                "Costa: 7.491 km de comprimento",
            ],
            [
                ("Qual é a capital do Brasil?",
                 ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador"], 2),
                ("Qual é a área da Floresta Amazónica?",
                 ["3,2 M km²", "5,5 M km²", "7,8 M km²", "9,1 M km²"], 1),
                ("Qual é o comprimento da costa do Brasil?",
                 ["4.230 km", "5.860 km", "7.491 km", "9.120 km"], 2),
            ],
        ),
        (
            "Austrália",
            [
                "População: 26,6 milhões (2024)",
                "Capital: Camberra (não Sydney)",
                "Área: 7.692.024 km² (6.º maior país)",
                "Grande Barreira de Coral: 2.300 km de comprimento",
                "Ponto mais alto: Monte Kosciuszko com 2.228 m",
                "87 % da população vive em áreas urbanas",
            ],
            [
                ("Qual é a população da Austrália?",
                 ["18,4 milhões", "26,6 milhões", "34,2 milhões", "42,8 milhões"], 1),
                ("Qual é o comprimento da Grande Barreira de Coral?",
                 ["1.200 km", "1.800 km", "2.300 km", "2.900 km"], 2),
                ("Que percentagem de australianos vive em áreas urbanas?",
                 ["72 %", "79 %", "87 %", "94 %"], 2),
            ],
        ),
        (
            "Suíça",
            [
                "População: 8,9 milhões (2024)",
                "Capital: Berna (não Zurique nem Genebra)",
                "4 línguas oficiais: alemão, francês, italiano, romanche",
                "Área: 41.285 km²",
                "Ponto mais alto: Ponta Dufour com 4.634 m",
                "PIB per capita: 99.994 $ (2.º mais alto do mundo)",
            ],
            [
                ("Qual é a capital da Suíça?",
                 ["Zurique", "Genebra", "Berna", "Basileia"], 2),
                ("Quantas línguas oficiais tem a Suíça?",
                 ["2", "3", "4", "5"], 2),
                ("Qual é o PIB per capita da Suíça?",
                 ["67.450 $", "82.310 $", "99.994 $", "115.200 $"], 2),
            ],
        ),
        (
            "Egito",
            [
                "População: 109,3 milhões (2024)",
                "Capital: Cairo (21,9 milhões de habitantes)",
                "Rio Nilo: 6.650 km (o mais longo de África)",
                "Grande Pirâmide: 146,6 metros de altura (originalmente)",
                "Área: 1.002.450 km² (97 % deserto)",
                "Canal de Suez: 193,3 km de comprimento, inaugurado em 1869",
            ],
            [
                ("Qual é a população do Cairo?",
                 ["14,2 milhões", "17,5 milhões", "21,9 milhões", "25,3 milhões"], 2),
                ("Qual é o comprimento do rio Nilo?",
                 ["4.130 km", "5.390 km", "6.650 km", "7.920 km"], 2),
                ("Qual é o comprimento do Canal de Suez?",
                 ["120,5 km", "156,8 km", "193,3 km", "231,7 km"], 2),
            ],
        ),
    ],
    "motivation": [
        (
            "A regra das 10.000 horas",
            [
                "Popularizada por Malcolm Gladwell em Outliers (2008)",
                "Baseada na investigação de K. Anders Ericsson",
                "Violinistas de elite tinham 10.000 horas de prática aos 20 anos",
                "A prática deliberada importa mais que o total de horas",
                "Os melhores praticam 4 horas/dia com concentração total",
                "Os ciclos de feedback aceleram a aprendizagem em 26 %",
            ],
            [
                ("Quem popularizou a regra das 10.000 horas?",
                 ["Daniel Kahneman", "Malcolm Gladwell", "Cal Newport", "James Clear"], 1),
                ("Quantas horas/dia praticam os melhores?",
                 ["2 horas", "4 horas", "6 horas", "8 horas"], 1),
                ("Quanto os ciclos de feedback aceleram a aprendizagem?",
                 ["12 %", "18 %", "26 %", "35 %"], 2),
            ],
        ),
        (
            "Investigação sobre mentalidade de crescimento",
            [
                "Cunhado por Carol Dweck na Universidade de Stanford",
                "Alunos elogiados pelo esforço melhoraram 30 % mais",
                "Mentalidade fixa: a inteligência é estática",
                "Mentalidade de crescimento: as capacidades desenvolvem-se com dedicação",
                "73 % dos principais CEO identificam-se com mentalidade de crescimento",
                "Intervenções de mentalidade elevaram as médias em 0,3 pontos",
            ],
            [
                ("Quem cunhou o termo 'mentalidade de crescimento'?",
                 ["Angela Duckworth", "Carol Dweck", "Martin Seligman", "Amy Cuddy"], 1),
                ("Quanto mais melhoraram os alunos elogiados pelo esforço?",
                 ["10 %", "20 %", "30 %", "40 %"], 2),
                ("Que percentagem dos principais CEO têm mentalidade de crescimento?",
                 ["53 %", "63 %", "73 %", "83 %"], 2),
            ],
        ),
        (
            "O poder dos hábitos",
            [
                "40 % das ações diárias são hábitos",
                "Ciclo do hábito: sinal → rotina → recompensa (Duhigg)",
                "Formar um novo hábito demora em média 66 dias",
                "As intenções de implementação aumentam o sucesso em 91 %",
                "Os hábitos-chave desencadeiam mudanças positivas em cascata",
                "Empilhamento de hábitos: ligar novos hábitos aos existentes",
            ],
            [
                ("Que percentagem das ações diárias são hábitos?",
                 ["20 %", "30 %", "40 %", "50 %"], 2),
                ("Quantos dias demora a formar um novo hábito em média?",
                 ["21 dias", "45 dias", "66 dias", "90 dias"], 2),
                ("Quanto as intenções de implementação aumentam o sucesso?",
                 ["51 %", "71 %", "81 %", "91 %"], 3),
            ],
        ),
        (
            "Estado de flow e desempenho",
            [
                "Conceito desenvolvido por Mihaly Csikszentmihalyi em 1975",
                "O flow aumenta a produtividade até 500 %",
                "Requer equilíbrio desafio-competência (4 % acima do nível atual)",
                "Tempo médio para entrar em flow: 15–20 minutos",
                "As interrupções reiniciam completamente o temporizador de flow",
                "O flow ativa 5 neuroquímicos: dopamina, noradrenalina, endorfinas, anandamida, serotonina",
            ],
            [
                ("Quem desenvolveu o conceito de flow?",
                 ["Daniel Pink", "Mihaly Csikszentmihalyi", "Cal Newport", "Adam Grant"], 1),
                ("Quanto pode o flow aumentar a produtividade?",
                 ["100 %", "200 %", "350 %", "500 %"], 3),
                ("Quanto tempo demora a entrar em flow?",
                 ["5–10 minutos", "15–20 minutos", "25–30 minutos", "35–40 minutos"], 1),
            ],
        ),
        (
            "Determinação e perseverança",
            [
                "Investigada por Angela Duckworth na UPenn",
                "A determinação prevê o sucesso melhor que o QI em 78 % dos estudos",
                "Cadetes de West Point: a pontuação de determinação previa a taxa de conclusão",
                "Determinação = paixão + persistência sustentada ao longo dos anos",
                "Pessoas determinadas praticam 32 % mais horas por semana",
                "A determinação pode ser desenvolvida — não é puramente inata",
            ],
            [
                ("Quem investigou a determinação?",
                 ["Carol Dweck", "Angela Duckworth", "Martin Seligman", "Dan Pink"], 1),
                ("Em que percentagem de estudos a determinação supera o QI?",
                 ["58 %", "68 %", "78 %", "88 %"], 2),
                ("Quanto mais praticam as pessoas determinadas por semana?",
                 ["12 %", "22 %", "32 %", "42 %"], 2),
            ],
        ),
    ],
    "neuroplasticity": [
        (
            "Bases da neuroplasticidade",
            [
                "O cérebro forma 1 milhão de novas conexões/segundo na infância",
                "Os adultos geram ~700 novos neurónios/dia no hipocampo",
                "Os taxistas de Londres têm hipocampos posteriores 16 % maiores",
                "A neuroplasticidade atinge o pico antes dos 25 anos",
                "Aprender uma nova competência aumenta a matéria cinzenta em 2 semanas",
                "O sono consolida as vias neurais — 7–9 horas ideal",
            ],
            [
                ("Quantos novos neurónios geram os adultos por dia?",
                 ["200", "500", "700", "1.000"], 2),
                ("Quanto maiores são os hipocampos dos taxistas?",
                 ["8 %", "12 %", "16 %", "22 %"], 2),
                ("Em quanto tempo a aprendizagem aumenta a matéria cinzenta?",
                 ["2 dias", "2 semanas", "2 meses", "6 meses"], 1),
            ],
        ),
        (
            "Formação da memória",
            [
                "A memória de curto prazo dura 15–30 segundos sem repetição",
                "Capacidade da memória de trabalho: 4 ± 1 elementos",
                "Consolidação: o hipocampo transfere para o neocórtex durante o sono",
                "A repetição espaçada melhora a retenção em 200 %",
                "As memórias emocionais são 3× mais fortes (envolvimento da amígdala)",
                "A técnica do palácio da memória melhora a recordação em 80 %",
            ],
            [
                ("Quanto dura a memória de curto prazo sem repetição?",
                 ["5–10 s", "15–30 s", "45–60 s", "2–3 min"], 1),
                ("Quanto a repetição espaçada melhora a retenção?",
                 ["50 %", "100 %", "200 %", "300 %"], 2),
                ("Quanto o palácio da memória melhora a recordação?",
                 ["40 %", "60 %", "80 %", "100 %"], 2),
            ],
        ),
        (
            "Exercício e cérebro",
            [
                "30 min de aeróbica aumentam o BDNF em 32 %",
                "O exercício regular aumenta o hipocampo em 2 %",
                "O exercício melhora as funções executivas em 20 %",
                "Benefícios cognitivos ótimos: 150 min de exercício moderado/semana",
                "O exercício após a aprendizagem melhora a retenção em 10 %",
                "A forma física reduz o risco de demência em 30 %",
            ],
            [
                ("Quanto 30 min de aeróbica aumentam o BDNF?",
                 ["12 %", "22 %", "32 %", "42 %"], 2),
                ("Quanto o exercício aumenta o hipocampo?",
                 ["0,5 %", "1 %", "2 %", "4 %"], 2),
                ("Quantos minutos de exercício moderado por semana são ótimos?",
                 ["60 min", "90 min", "150 min", "200 min"], 2),
            ],
        ),
        (
            "Meditação e mudanças neurais",
            [
                "8 semanas de meditação aumentam a densidade de matéria cinzenta",
                "Os meditadores mostram 25 % mais atividade no córtex pré-frontal",
                "A atenção plena reduz o volume da amígdala em 5 %",
                "Meditadores de longo prazo: 50 % mais atividade de ondas gama",
                "A meditação melhora a capacidade de atenção em 14 %",
                "12 min de prática diária mostram mudanças cerebrais mensuráveis",
            ],
            [
                ("Quanta mais atividade pré-frontal mostram os meditadores?",
                 ["10 %", "15 %", "25 %", "35 %"], 2),
                ("Quanto a atenção plena reduz o volume da amígdala?",
                 ["2 %", "5 %", "8 %", "12 %"], 1),
                ("Quantos minutos de meditação diária mostram efeitos mensuráveis?",
                 ["5 min", "8 min", "12 min", "20 min"], 2),
            ],
        ),
        (
            "Bilinguismo e cognição",
            [
                "Os bilingues mudam de tarefa 4,5 vezes mais rápido",
                "O início da demência é atrasado 4–5 anos nos bilingues",
                "Os cérebros bilingues têm matéria cinzenta mais densa no CCA",
                "Controlo executivo: 15 % melhor nos bilingues",
                "Período crítico para aquisição linguística: antes dos 7 anos",
                "Os bilingues mostram capacidade superior de memória de trabalho",
            ],
            [
                ("Quanto mais rápido os bilingues mudam de tarefa?",
                 ["2,5×", "3,5×", "4,5×", "5,5×"], 2),
                ("Quantos anos o bilinguismo atrasa a demência?",
                 ["1–2 anos", "2–3 anos", "4–5 anos", "6–7 anos"], 2),
                ("Até que idade dura o período crítico para as línguas?",
                 ["5 anos", "7 anos", "10 anos", "12 anos"], 1),
            ],
        ),
    ],
    "humor": [
        (
            "A ciência do riso",
            [
                "Um adulto médio ri 17 vezes por dia",
                "Rir queima 10–40 calorias em 15 minutos",
                "Os bebés começam a rir por volta dos 4 meses",
                "O riso liberta endorfinas e reduz o cortisol em 39 %",
                "Gelotologia: o estudo científico do riso",
                "O riso é contagioso — 30× mais provável em grupo",
            ],
            [
                ("Quantas vezes ri um adulto médio por dia?",
                 ["7 vezes", "12 vezes", "17 vezes", "25 vezes"], 2),
                ("Quanto o riso reduz o cortisol?",
                 ["19 %", "29 %", "39 %", "49 %"], 2),
                ("Como se chama a ciência do riso?",
                 ["Humorologia", "Gelotologia", "Risologia", "Comicologia"], 1),
            ],
        ),
        (
            "Factos curiosos sobre animais",
            [
                "Os polvos têm 3 corações e sangue azul",
                "Um beija-flor pesa menos que uma moeda de 5 cêntimos",
                "As vacas têm melhores amigas e ficam stressadas sem elas",
                "Os golfinhos dormem com um olho aberto",
                "Os flamingos só são cor-de-rosa por causa da dieta de camarões",
                "As preguiças demoram 2 semanas a digerir a comida",
            ],
            [
                ("Quantos corações tem um polvo?",
                 ["1", "2", "3", "4"], 2),
                ("Porque são os flamingos cor-de-rosa?",
                 ["Genética", "Luz solar", "Dieta de camarões", "Química da água"], 2),
                ("Quanto demoram as preguiças a digerir?",
                 ["3 dias", "1 semana", "2 semanas", "1 mês"], 2),
            ],
        ),
        (
            "Recordes mundiais absurdos",
            [
                "Soluço mais longo: 68 anos (Charles Osborne)",
                "Mais t-shirts vestidas ao mesmo tempo: 260",
                "Corrida para trás mais rápida: 100 m em 13,6 segundos",
                "Unha mais longa alguma vez medida: 8,65 metros",
                "Mais cachorros-quentes comidos em 10 min: 76",
                "Ressonar mais alto registado: 93 decibéis",
            ],
            [
                ("Quanto durou o soluço mais longo?",
                 ["12 anos", "34 anos", "68 anos", "85 anos"], 2),
                ("Quantas t-shirts foram vestidas ao mesmo tempo?",
                 ["120", "185", "260", "340"], 2),
                ("Quantos decibéis tinha o ressonar mais alto?",
                 ["73 dB", "83 dB", "93 dB", "103 dB"], 2),
            ],
        ),
        (
            "Curiosidades alimentares",
            [
                "O mel nunca estraga — mel de 3.000 anos ainda era comestível",
                "As bananas são botanicamente bagas, os morangos não",
                "O ketchup era vendido como medicamento na década de 1830",
                "Um humano médio come 35 toneladas de comida na vida",
                "O wasabi nos restaurantes é geralmente rábano colorido",
                "Um ananás demora 2–3 anos a crescer",
            ],
            [
                ("Que idade tinha o mel mais antigo ainda comestível?",
                 ["500 anos", "1.000 anos", "3.000 anos", "5.000 anos"], 2),
                ("Quanta comida come um humano médio na vida?",
                 ["15 toneladas", "25 toneladas", "35 toneladas", "50 toneladas"], 2),
                ("Quanto demora um ananás a crescer?",
                 ["6 meses", "1 ano", "2–3 anos", "5 anos"], 2),
            ],
        ),
        (
            "Inútil mas verdadeiro",
            [
                "Um relâmpago é 5× mais quente que a superfície do Sol",
                "A Terra gira a 1.670 km/h no equador",
                "Os ossos humanos são mais fortes que o aço (por peso)",
                "Há mais estrelas no universo que grãos de areia na Terra",
                "O estômago renova a sua mucosa a cada 3–4 dias",
                "A Universidade de Oxford é mais antiga que o Império Asteca",
            ],
            [
                ("Quanto mais quente é um relâmpago que a superfície do Sol?",
                 ["2×", "3×", "5×", "8×"], 2),
                ("A que velocidade gira a Terra no equador?",
                 ["670 km/h", "1.070 km/h", "1.670 km/h", "2.270 km/h"], 2),
                ("Com que frequência se renova a mucosa do estômago?",
                 ["A cada 1–2 dias", "A cada 3–4 dias", "A cada 7 dias", "A cada 14 dias"], 1),
            ],
        ),
    ],
    "history": [
        (
            "A Roma Antiga",
            [
                "Fundação: 753 a.C. (segundo a lenda)",
                "População máxima: 1 milhão (século I d.C.)",
                "Rede de estradas: 400.000 km em todo o império",
                "O Coliseu albergava 50.000–80.000 espetadores",
                "Os aquedutos transportavam 1 milhão de m³ de água por dia",
                "O Império durou mais de 1.000 anos (753 a.C. – 476 d.C.)",
            ],
            [
                ("Quando foi Roma fundada segundo a lenda?",
                 ["509 a.C.", "753 a.C.", "264 a.C.", "1.000 a.C."], 1),
                ("Quantos espetadores albergava o Coliseu?",
                 ["20.000–30.000", "35.000–45.000", "50.000–80.000", "90.000–100.000"], 2),
                ("Qual era o comprimento da rede de estradas romana?",
                 ["100.000 km", "250.000 km", "400.000 km", "600.000 km"], 2),
            ],
        ),
        (
            "A alunagem",
            [
                "Data: 20 de julho de 1969 (Apollo 11)",
                "Primeiras palavras na Lua: Neil Armstrong",
                "Duração da missão: 8 dias 3 horas 18 minutos",
                "Distância Terra–Lua: 384.400 km",
                "Rochas lunares trazidas: 21,55 kg",
                "Custo estimado: 25,4 mil milhões $ (dólares de 1973)",
            ],
            [
                ("Quando foi a primeira alunagem?",
                 ["15 de março de 1968", "20 de julho de 1969", "12 de abril de 1970", "3 de junho de 1971"], 1),
                ("Quantas rochas lunares foram trazidas?",
                 ["8,2 kg", "15,3 kg", "21,55 kg", "34,7 kg"], 2),
                ("Qual é a distância Terra–Lua?",
                 ["284.400 km", "384.400 km", "484.400 km", "584.400 km"], 1),
            ],
        ),
        (
            "Segunda Guerra Mundial — Números-chave",
            [
                "Duração: 1939–1945 (6 anos)",
                "Nações envolvidas: mais de 30",
                "Vítimas totais estimadas: 70–85 milhões",
                "Dia D: 6 de junho de 1944 — 156.000 soldados aliados",
                "Custo: estimado em 1,657 biliões $ (dólares de 1945)",
                "Fim na Europa: 8 de maio de 1945 (Dia da Vitória)",
            ],
            [
                ("Quantas nações estiveram envolvidas na 2.ª Guerra Mundial?",
                 ["Mais de 10", "Mais de 20", "Mais de 30", "Mais de 50"], 2),
                ("Quantos soldados aliados desembarcaram no Dia D?",
                 ["75.000", "120.000", "156.000", "200.000"], 2),
                ("Quando terminou a guerra na Europa?",
                 ["8 de maio de 1945", "2 de setembro de 1945", "15 de agosto de 1945", "11 de novembro de 1944"], 0),
            ],
        ),
        (
            "O Renascimento",
            [
                "Período: aprox. 1350–1600 d.C.",
                "Origem: Florença, Itália",
                "Leonardo da Vinci pintou a Mona Lisa aprox. 1503–1519",
                "A imprensa de Gutenberg: aprox. 1440",
                "O teto da Capela Sistina de Miguel Ângelo: 1508–1512",
                "População da Europa: ~60 milhões após a peste",
            ],
            [
                ("Onde começou o Renascimento?",
                 ["Paris", "Roma", "Florença", "Veneza"], 2),
                ("Quando Gutenberg inventou a imprensa?",
                 ["aprox. 1380", "aprox. 1440", "aprox. 1500", "aprox. 1550"], 1),
                ("Quanto tempo Miguel Ângelo demorou a pintar o teto da Sistina?",
                 ["1 ano", "2 anos", "4 anos", "8 anos"], 2),
            ],
        ),
        (
            "A Revolução Industrial",
            [
                "Início: aprox. 1760 na Grã-Bretanha",
                "Máquina a vapor de Watt: patenteada em 1769",
                "Primeiro caminho de ferro: Stockton–Darlington em 1825",
                "População urbana cresceu de 20 % para 50 % até 1850",
                "Trabalho infantil: crianças a partir dos 5 anos trabalhavam turnos de 16 horas",
                "A produção de algodão aumentou 800 % entre 1770 e 1800",
            ],
            [
                ("Onde começou a Revolução Industrial?",
                 ["França", "Alemanha", "Grã-Bretanha", "EUA"], 2),
                ("Quando foi patenteada a máquina a vapor de Watt?",
                 ["1745", "1769", "1785", "1801"], 1),
                ("Quanto aumentou a produção de algodão 1770–1800?",
                 ["200 %", "400 %", "800 %", "1.200 %"], 2),
            ],
        ),
    ],
    "nutrition": [
        (
            "Macronutrientes",
            [
                "Hidratos de carbono: 4 calorias por grama",
                "Proteínas: 4 calorias por grama",
                "Gorduras: 9 calorias por grama",
                "Distribuição recomendada: 45–65 % hidratos, 20–35 % gorduras, 10–35 % proteínas",
                "Fibra: 25–30 g por dia recomendados",
                "Um adulto médio precisa de 2.000–2.500 kcal/dia",
            ],
            [
                ("Quantas calorias tem um grama de gordura?",
                 ["4", "7", "9", "12"], 2),
                ("Quanta fibra por dia é recomendada?",
                 ["10–15 g", "15–20 g", "25–30 g", "35–40 g"], 2),
                ("Que percentagem de calorias deve vir dos hidratos de carbono?",
                 ["25–40 %", "45–65 %", "60–80 %", "70–90 %"], 1),
            ],
        ),
        (
            "Factos sobre hidratação",
            [
                "Corpo humano: 60 % de água",
                "Cérebro e coração: 73 % de água",
                "Ingestão recomendada: 2,7–3,7 litros/dia (incluindo alimentos)",
                "2 % de desidratação reduz o desempenho cognitivo em 25 %",
                "Os rins filtram 180 litros de sangue por dia",
                "A cafeína é um diurético leve — o efeito líquido é mínimo",
            ],
            [
                ("Que percentagem do corpo é água?",
                 ["45 %", "52 %", "60 %", "70 %"], 2),
                ("Quanto 2 % de desidratação reduz o desempenho cognitivo?",
                 ["10 %", "15 %", "25 %", "35 %"], 2),
                ("Quantos litros de sangue filtram os rins por dia?",
                 ["90 litros", "120 litros", "180 litros", "240 litros"], 2),
            ],
        ),
        (
            "Vitaminas e minerais",
            [
                "Vitamina D: 1 mil milhão de pessoas no mundo têm deficiência",
                "Ferro: 25 % da população mundial tem deficiência de ferro",
                "Vitamina C: 90 mg/dia recomendados para adultos",
                "Cálcio: 99 % está armazenado nos ossos e dentes",
                "B12: encontrada naturalmente apenas em produtos animais",
                "Zinco: apoia mais de 300 reações enzimáticas",
            ],
            [
                ("Quantas pessoas têm deficiência de vitamina D no mundo?",
                 ["100 milhões", "500 milhões", "1 mil milhão", "2 mil milhões"], 2),
                ("Quanta vitamina C por dia é recomendada?",
                 ["45 mg", "60 mg", "90 mg", "120 mg"], 2),
                ("Que percentagem do cálcio está nos ossos e dentes?",
                 ["85 %", "92 %", "99 %", "100 %"], 2),
            ],
        ),
        (
            "Conexão intestino-cérebro",
            [
                "O intestino contém 500 milhões de neurónios",
                "95 % da serotonina é produzida no intestino",
                "Microbioma intestinal: 100 biliões de bactérias",
                "Nervo vago: conexão direta entre intestino e cérebro",
                "A saúde intestinal influencia o humor, o sono e a cognição",
                "Os probióticos podem reduzir os sintomas de ansiedade em 20 %",
            ],
            [
                ("Quantos neurónios contém o intestino?",
                 ["100 milhões", "300 milhões", "500 milhões", "800 milhões"], 2),
                ("Que percentagem da serotonina é produzida no intestino?",
                 ["50 %", "75 %", "85 %", "95 %"], 3),
                ("Quanto os probióticos podem reduzir os sintomas de ansiedade?",
                 ["10 %", "15 %", "20 %", "30 %"], 2),
            ],
        ),
        (
            "Cafeína e desempenho",
            [
                "A cafeína bloqueia os recetores de adenosina no cérebro",
                "Início do efeito: 15–45 minutos após a ingestão",
                "Meia-vida: 5–6 horas em média",
                "Dose ótima: 3–6 mg/kg de peso corporal",
                "Melhora o tempo de reação em 11 %",
                "Dose diária segura: até 400 mg (cerca de 4 chávenas de café)",
            ],
            [
                ("Quanto tempo demora a cafeína a fazer efeito?",
                 ["5–10 min", "15–45 min", "60–90 min", "2–3 horas"], 1),
                ("Quanto a cafeína melhora o tempo de reação?",
                 ["5 %", "8 %", "11 %", "15 %"], 2),
                ("Quanta cafeína por dia é considerada segura?",
                 ["200 mg", "300 mg", "400 mg", "500 mg"], 2),
            ],
        ),
    ],
}
