"""German slide library for Slide Processing exercise."""

SLIDE_LIBRARY = {
    "science": [
        (
            "Das menschliche Gehirn",
            [
                "Gewicht: 1,4 kg (etwa 2 % des Körpergewichts)",
                "Enthält ungefähr 86 Milliarden Neuronen",
                "Verbraucht 20 % der gesamten Körperenergie",
                "Erzeugt etwa 23 Watt elektrische Leistung",
                "Verarbeitungsgeschwindigkeit: bis zu 120 m/s",
                "Speicherkapazität: geschätzt 2,5 Petabyte",
            ],
            [
                ("Wie viele Neuronen enthält das Gehirn?",
                 ["12 Milliarden", "86 Milliarden", "100 Milliarden", "45 Milliarden"], 1),
                ("Wie viel Prozent der Körperenergie verbraucht das Gehirn?",
                 ["10 %", "15 %", "20 %", "30 %"], 2),
                ("Wie hoch ist die geschätzte Speicherkapazität?",
                 ["1,5 Petabyte", "2,5 Petabyte", "5 Petabyte", "500 Terabyte"], 1),
            ],
        ),
        (
            "Mars-Erkundung",
            [
                "Entfernung zur Erde: 54,6 bis 401 Millionen km",
                "Oberflächentemperatur: −87 °C bis −5 °C",
                "Olympus Mons: höchster Vulkan mit 21,9 km",
                "Tageslänge (Sol): 24 Stunden 37 Minuten",
                "Atmosphäre: 95,3 % Kohlendioxid",
                "Schwerkraft: 3,72 m/s² (38 % der Erde)",
            ],
            [
                ("Wie hoch ist der Olympus Mons?",
                 ["15,2 km", "18,6 km", "21,9 km", "25,1 km"], 2),
                ("Wie viel Prozent der Mars-Atmosphäre ist CO₂?",
                 ["78,1 %", "89,7 %", "95,3 %", "99,2 %"], 2),
                ("Wie stark ist die Mars-Schwerkraft verglichen mit der Erde?",
                 ["28 %", "38 %", "48 %", "58 %"], 1),
            ],
        ),
        (
            "Fakten über die Ozeane",
            [
                "Ozeane bedecken 71 % der Erdoberfläche",
                "Durchschnittliche Tiefe: 3.688 Meter",
                "Tiefster Punkt: Marianengraben mit 10.994 m",
                "Enthält 97 % des Wassers der Erde",
                "Pazifischer Ozean: größter mit 165,25 Mio. km²",
                "Wassertemperatur: −2 °C bis 36 °C",
            ],
            [
                ("Wie tief ist der Ozean durchschnittlich?",
                 ["2.450 m", "3.688 m", "4.200 m", "5.100 m"], 1),
                ("Wie viel Prozent des Erdwassers ist in den Ozeanen?",
                 ["87 %", "92 %", "97 %", "99 %"], 2),
                ("Wie tief ist der Marianengraben?",
                 ["8.848 m", "9.500 m", "10.994 m", "12.100 m"], 2),
            ],
        ),
        (
            "Lichtgeschwindigkeit",
            [
                "Geschwindigkeit im Vakuum: 299.792.458 m/s",
                "Licht legt 9,461 Billionen km pro Jahr zurück",
                "Sonnenlicht erreicht die Erde in 8 Min 20 Sek",
                "Licht vom Mond: 1,3 Sekunden zur Erde",
                "Nächster Stern (Proxima Centauri): 4,24 Lichtjahre",
                "Licht verlangsamt sich auf 225.000 km/s in Wasser",
            ],
            [
                ("Wie lange braucht Sonnenlicht zur Erde?",
                 ["4 Min 10 Sek", "6 Min 45 Sek", "8 Min 20 Sek", "12 Min 5 Sek"], 2),
                ("Wie weit ist Proxima Centauri in Lichtjahren?",
                 ["2,18", "4,24", "6,71", "8,60"], 1),
                ("Wie schnell ist Licht in Wasser?",
                 ["150.000 km/s", "225.000 km/s", "275.000 km/s", "299.792 km/s"], 1),
            ],
        ),
        (
            "DNA und Genetik",
            [
                "Menschliches Genom: 3,2 Milliarden Basenpaare",
                "Menschen teilen 98,7 % der DNA mit Schimpansen",
                "Jede Zelle enthält etwa 2 Meter DNA",
                "Nur 1,5 % der DNA kodiert für Proteine",
                "23 Chromosomenpaare in menschlichen Zellen",
                "DNA-Replikation: 1.000 Nukleotide/Sekunde",
            ],
            [
                ("Wie viele Basenpaare hat das menschliche Genom?",
                 ["1,8 Mrd.", "3,2 Mrd.", "4,6 Mrd.", "6,4 Mrd."], 1),
                ("Wie viel Prozent der DNA kodiert für Proteine?",
                 ["1,5 %", "5 %", "10 %", "25 %"], 0),
                ("Wie viel DNA enthält jede Zelle?",
                 ["0,5 Meter", "2 Meter", "5 Meter", "10 Meter"], 1),
            ],
        ),
    ],
    "business": [
        (
            "Globaler Kaffeemarkt 2024",
            [
                "Marktwert: 495,2 Milliarden Dollar",
                "Jährlicher Verbrauch: 10,5 Milliarden kg weltweit",
                "Größter Produzent: Brasilien (37,4 % der Weltproduktion)",
                "Durchschnittspreis pro kg: 14,80 $ (Arabica)",
                "Spezialitätenkaffee wächst mit 12,3 % CAGR",
                "Finnland führt beim Pro-Kopf-Verbrauch: 12 kg/Jahr",
            ],
            [
                ("Wie hoch ist der globale Kaffeemarkt-Wert?",
                 ["312,8 Mrd. $", "495,2 Mrd. $", "620,5 Mrd. $", "780,1 Mrd. $"], 1),
                ("Wie viel Prozent des Kaffees produziert Brasilien?",
                 ["22,1 %", "29,8 %", "37,4 %", "45,6 %"], 2),
                ("Welches Land führt beim Pro-Kopf-Kaffeeverbrauch?",
                 ["Italien", "Kolumbien", "Finnland", "USA"], 2),
            ],
        ),
        (
            "Elektrofahrzeug-Verkäufe",
            [
                "Globale EV-Verkäufe 2024: 17,1 Millionen Einheiten",
                "Marktanteil: 22 % aller Neuwagen",
                "China führt mit 59 % der globalen EV-Verkäufe",
                "Durchschnittliche EV-Batteriekosten: 139 $/kWh",
                "Tesla-Marktanteil: 18,4 % der globalen EVs",
                "Durchschnittliche EV-Reichweite: 348 km pro Ladung",
            ],
            [
                ("Wie viele EVs wurden 2024 weltweit verkauft?",
                 ["9,8 Mio.", "13,5 Mio.", "17,1 Mio.", "21,4 Mio."], 2),
                ("Wie hoch ist Chinas Anteil an globalen EV-Verkäufen?",
                 ["35 %", "47 %", "59 %", "72 %"], 2),
                ("Was kosten EV-Batterien durchschnittlich pro kWh?",
                 ["89 $", "139 $", "189 $", "239 $"], 1),
            ],
        ),
        (
            "Homeoffice-Statistiken",
            [
                "32,6 Mio. Amerikaner arbeiten 2025 remote",
                "Produktivitätssteigerung: 13 % bei Remote-Arbeitern",
                "Eingesparte Pendelzeit: 72 Minuten/Tag",
                "Unternehmen sparen 11.000 $ pro Remote-Mitarbeiter/Jahr",
                "67 % berichten über bessere Work-Life-Balance",
                "Videokonferenz-Markt: 13,8 Milliarden Dollar",
            ],
            [
                ("Wie viel Pendelzeit sparen Remote-Arbeiter täglich?",
                 ["45 Minuten", "72 Minuten", "90 Minuten", "120 Minuten"], 1),
                ("Wie viel sparen Unternehmen pro Remote-Mitarbeiter?",
                 ["5.000 $", "8.500 $", "11.000 $", "15.000 $"], 2),
                ("Wie hoch ist die Produktivitätssteigerung bei Remote-Arbeit?",
                 ["8 %", "13 %", "18 %", "25 %"], 1),
            ],
        ),
        (
            "Smartphone-Markt Q4 2024",
            [
                "Globale Auslieferungen: 328,2 Millionen Einheiten",
                "Samsung: 19,4 % Marktanteil (Nr. 1)",
                "Apple: 18,2 % Marktanteil (Nr. 2)",
                "Durchschnittlicher Verkaufspreis: 322 $",
                "5G-Telefone: 78 % aller Auslieferungen",
                "Faltbare Telefone wuchsen 49 % im Jahresvergleich",
            ],
            [
                ("Wie viele Smartphones wurden in Q4 2024 ausgeliefert?",
                 ["245,6 Mio.", "328,2 Mio.", "412,7 Mio.", "501,3 Mio."], 1),
                ("Wie hoch war Samsungs Marktanteil?",
                 ["15,8 %", "19,4 %", "23,1 %", "27,6 %"], 1),
                ("Wie viel Prozent der Auslieferungen waren 5G-Telefone?",
                 ["58 %", "68 %", "78 %", "88 %"], 2),
            ],
        ),
        (
            "Globaler Tourismus 2024",
            [
                "Internationale Ankünfte: 1,4 Milliarden",
                "Tourismuseinnahmen: 1,9 Billionen Dollar",
                "Meistbesuchtes Land: Frankreich (100 Mio. Besucher)",
                "Durchschnittliche Ausgaben pro Tourist: 1.350 $",
                "Tourismus beschäftigt 330 Millionen Menschen weltweit",
                "Asien-Pazifik-Wachstum: 18 % im Jahresvergleich",
            ],
            [
                ("Wie viele internationale Touristenankünfte gab es 2024?",
                 ["0,8 Mrd.", "1,1 Mrd.", "1,4 Mrd.", "1,8 Mrd."], 2),
                ("Welches Land hatte die meisten Besucher?",
                 ["Spanien", "USA", "Frankreich", "Italien"], 2),
                ("Wie viele Menschen beschäftigt der Tourismus weltweit?",
                 ["180 Mio.", "250 Mio.", "330 Mio.", "420 Mio."], 2),
            ],
        ),
    ],
    "geography": [
        (
            "Japan",
            [
                "Bevölkerung: 123,3 Millionen (2024)",
                "Hauptstadt: Tokio (13,96 Millionen Einwohner)",
                "Fläche: 377.975 km²",
                "Höchster Punkt: Berg Fuji mit 3.776 Metern",
                "BIP pro Kopf: 33.950 $",
                "Lebenserwartung: 84,8 Jahre (weltweit höchste)",
            ],
            [
                ("Wie groß ist Japans Bevölkerung?",
                 ["98,5 Mio.", "123,3 Mio.", "145,7 Mio.", "168,2 Mio."], 1),
                ("Wie hoch ist der Berg Fuji?",
                 ["2.954 m", "3.776 m", "4.421 m", "5.108 m"], 1),
                ("Wie hoch ist Japans Lebenserwartung?",
                 ["78,2 Jahre", "81,5 Jahre", "84,8 Jahre", "87,3 Jahre"], 2),
            ],
        ),
        (
            "Brasilien",
            [
                "Bevölkerung: 216,4 Millionen (2024)",
                "Hauptstadt: Brasília (nicht São Paulo oder Rio)",
                "Fläche: 8.515.767 km² (5.-größtes Land)",
                "Amazonas-Regenwald: 5,5 Millionen km²",
                "Amtssprache: Portugiesisch",
                "Küstenlinie: 7.491 km lang",
            ],
            [
                ("Was ist Brasiliens Hauptstadt?",
                 ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador"], 2),
                ("Wie groß ist der Amazonas-Regenwald?",
                 ["3,2 Mio. km²", "5,5 Mio. km²", "7,8 Mio. km²", "9,1 Mio. km²"], 1),
                ("Wie lang ist Brasiliens Küstenlinie?",
                 ["4.230 km", "5.860 km", "7.491 km", "9.120 km"], 2),
            ],
        ),
        (
            "Australien",
            [
                "Bevölkerung: 26,6 Millionen (2024)",
                "Hauptstadt: Canberra (nicht Sydney)",
                "Fläche: 7.692.024 km² (6.-größtes Land)",
                "Great Barrier Reef: 2.300 km lang",
                "Höchster Punkt: Mount Kosciuszko mit 2.228 m",
                "87 % der Bevölkerung lebt in Städten",
            ],
            [
                ("Wie groß ist Australiens Bevölkerung?",
                 ["18,4 Mio.", "26,6 Mio.", "34,2 Mio.", "42,8 Mio."], 1),
                ("Wie lang ist das Great Barrier Reef?",
                 ["1.200 km", "1.800 km", "2.300 km", "2.900 km"], 2),
                ("Wie viel Prozent der Australier leben in Städten?",
                 ["72 %", "79 %", "87 %", "94 %"], 2),
            ],
        ),
        (
            "Schweiz",
            [
                "Bevölkerung: 8,9 Millionen (2024)",
                "Hauptstadt: Bern (nicht Zürich oder Genf)",
                "4 Amtssprachen: Deutsch, Französisch, Italienisch, Rätoromanisch",
                "Fläche: 41.285 km²",
                "Höchster Punkt: Dufourspitze mit 4.634 m",
                "BIP pro Kopf: 99.994 $ (weltweit 2.-höchstes)",
            ],
            [
                ("Was ist die Hauptstadt der Schweiz?",
                 ["Zürich", "Genf", "Bern", "Basel"], 2),
                ("Wie viele Amtssprachen hat die Schweiz?",
                 ["2", "3", "4", "5"], 2),
                ("Wie hoch ist das BIP pro Kopf der Schweiz?",
                 ["67.450 $", "82.310 $", "99.994 $", "115.200 $"], 2),
            ],
        ),
        (
            "Ägypten",
            [
                "Bevölkerung: 109,3 Millionen (2024)",
                "Hauptstadt: Kairo (21,9 Millionen Einwohner)",
                "Nil: 6.650 km (längster Fluss Afrikas)",
                "Große Pyramide: ursprünglich 146,6 Meter hoch",
                "Fläche: 1.002.450 km² (97 % Wüste)",
                "Suezkanal: 193,3 km lang, eröffnet 1869",
            ],
            [
                ("Wie viele Einwohner hat Kairo?",
                 ["14,2 Mio.", "17,5 Mio.", "21,9 Mio.", "25,3 Mio."], 2),
                ("Wie lang ist der Nil?",
                 ["4.130 km", "5.390 km", "6.650 km", "7.920 km"], 2),
                ("Wie lang ist der Suezkanal?",
                 ["120,5 km", "156,8 km", "193,3 km", "231,7 km"], 2),
            ],
        ),
    ],
    "motivation": [
        (
            "Die 10.000-Stunden-Regel",
            [
                "Populär gemacht durch Malcolm Gladwell in Outliers (2008)",
                "Basiert auf Forschung von K. Anders Ericsson",
                "Elite-Violinisten übten bis zum 20. Lebensjahr 10.000 Stunden",
                "Bewusstes Üben zählt mehr als die Gesamtstunden",
                "Spitzenleister üben 4 Stunden/Tag mit voller Konzentration",
                "Feedback-Schleifen beschleunigen den Lernprozess um 26 %",
            ],
            [
                ("Wer machte die 10.000-Stunden-Regel populär?",
                 ["Daniel Kahneman", "Malcolm Gladwell", "Cal Newport", "James Clear"], 1),
                ("Wie viele Stunden/Tag üben Spitzenleister?",
                 ["2 Stunden", "4 Stunden", "6 Stunden", "8 Stunden"], 1),
                ("Um wie viel beschleunigen Feedback-Schleifen das Lernen?",
                 ["12 %", "18 %", "26 %", "35 %"], 2),
            ],
        ),
        (
            "Growth-Mindset-Forschung",
            [
                "Geprägt von Carol Dweck an der Stanford University",
                "Für Anstrengung gelobte Schüler verbesserten sich 30 % mehr",
                "Fixed Mindset: Intelligenz ist unveränderlich",
                "Growth Mindset: Fähigkeiten entwickeln sich durch Einsatz",
                "73 % der Top-CEOs bezeichnen sich als Growth-Mindset-Denker",
                "Mindset-Interventionen hoben den Notendurchschnitt um 0,3 Punkte",
            ],
            [
                ("Wer prägte den Begriff 'Growth Mindset'?",
                 ["Angela Duckworth", "Carol Dweck", "Martin Seligman", "Amy Cuddy"], 1),
                ("Um wie viel mehr verbesserten sich für Anstrengung gelobte Schüler?",
                 ["10 %", "20 %", "30 %", "40 %"], 2),
                ("Wie viel Prozent der Top-CEOs haben ein Growth Mindset?",
                 ["53 %", "63 %", "73 %", "83 %"], 2),
            ],
        ),
        (
            "Die Macht der Gewohnheiten",
            [
                "40 % der täglichen Handlungen sind Gewohnheiten",
                "Gewohnheitsschleife: Auslöser → Routine → Belohnung (Duhigg)",
                "Neue Gewohnheiten bilden sich in durchschnittlich 66 Tagen",
                "Umsetzungsabsichten erhöhen die Erfolgsrate um 91 %",
                "Schlüsselgewohnheiten lösen kaskadierende positive Veränderungen aus",
                "Habit Stacking: neue Gewohnheiten an bestehende knüpfen",
            ],
            [
                ("Wie viel Prozent der täglichen Handlungen sind Gewohnheiten?",
                 ["20 %", "30 %", "40 %", "50 %"], 2),
                ("Wie viele Tage braucht eine neue Gewohnheit im Durchschnitt?",
                 ["21 Tage", "45 Tage", "66 Tage", "90 Tage"], 2),
                ("Um wie viel erhöhen Umsetzungsabsichten den Erfolg?",
                 ["51 %", "71 %", "81 %", "91 %"], 3),
            ],
        ),
        (
            "Flow-Zustand und Leistung",
            [
                "Konzept entwickelt von Mihaly Csikszentmihalyi 1975",
                "Flow steigert die Produktivität um bis zu 500 %",
                "Erfordert Herausforderungs-Fähigkeits-Balance (4 % über aktuellem Niveau)",
                "Durchschnittliche Zeit bis zum Flow: 15–20 Minuten",
                "Unterbrechungen setzen den Flow-Timer komplett zurück",
                "Flow aktiviert 5 Neurochemikalien: Dopamin, Noradrenalin, Endorphine, Anandamid, Serotonin",
            ],
            [
                ("Wer entwickelte das Flow-Konzept?",
                 ["Daniel Pink", "Mihaly Csikszentmihalyi", "Cal Newport", "Adam Grant"], 1),
                ("Um wie viel kann Flow die Produktivität steigern?",
                 ["100 %", "200 %", "350 %", "500 %"], 3),
                ("Wie lange dauert es, in den Flow zu kommen?",
                 ["5–10 Minuten", "15–20 Minuten", "25–30 Minuten", "35–40 Minuten"], 1),
            ],
        ),
        (
            "Grit und Durchhaltevermögen",
            [
                "Erforscht von Angela Duckworth an der UPenn",
                "Grit sagt Erfolg besser voraus als IQ in 78 % der Studien",
                "West-Point-Kadetten: Grit-Score sagte Abschlussrate voraus",
                "Grit = Leidenschaft + anhaltende Ausdauer über Jahre",
                "Grittige Personen üben 32 % mehr Stunden pro Woche",
                "Grit kann entwickelt werden — es ist nicht rein angeboren",
            ],
            [
                ("Wer erforschte Grit?",
                 ["Carol Dweck", "Angela Duckworth", "Martin Seligman", "Dan Pink"], 1),
                ("In wie viel Prozent der Studien übertrifft Grit den IQ?",
                 ["58 %", "68 %", "78 %", "88 %"], 2),
                ("Wie viel mehr üben grittige Personen wöchentlich?",
                 ["12 %", "22 %", "32 %", "42 %"], 2),
            ],
        ),
    ],
    "neuroplasticity": [
        (
            "Grundlagen der Neuroplastizität",
            [
                "Das Gehirn bildet 1 Million neue Verbindungen pro Sekunde im Säuglingsalter",
                "Erwachsene erzeugen täglich ~700 neue Neuronen im Hippocampus",
                "Londoner Taxifahrer haben 16 % größere posteriore Hippocampi",
                "Neuroplastizität ist vor dem 25. Lebensjahr am höchsten",
                "Neue Fähigkeiten erhöhen die graue Substanz in 2 Wochen",
                "Schlaf festigt neuronale Bahnen — 7–9 Stunden optimal",
            ],
            [
                ("Wie viele neue Neuronen erzeugen Erwachsene täglich?",
                 ["200", "500", "700", "1.000"], 2),
                ("Um wie viel größer sind die Hippocampi von Taxifahrern?",
                 ["8 %", "12 %", "16 %", "22 %"], 2),
                ("Wie schnell kann Lernen die graue Substanz vermehren?",
                 ["2 Tage", "2 Wochen", "2 Monate", "6 Monate"], 1),
            ],
        ),
        (
            "Gedächtnisbildung",
            [
                "Kurzzeitgedächtnis hält 15–30 Sekunden ohne Wiederholung",
                "Arbeitsgedächtnis-Kapazität: 4 ± 1 Elemente (aktualisierte Forschung)",
                "Konsolidierung: Hippocampus überträgt an Neokortex im Schlaf",
                "Spaced Repetition verbessert Behalten um 200 %",
                "Emotionale Erinnerungen sind 3× stärker (Amygdala-Beteiligung)",
                "Gedächtnispalast-Technik verbessert Abruf um 80 %",
            ],
            [
                ("Wie lange hält das Kurzzeitgedächtnis ohne Wiederholung?",
                 ["5–10 Sek", "15–30 Sek", "45–60 Sek", "2–3 Min"], 1),
                ("Um wie viel verbessert Spaced Repetition das Behalten?",
                 ["50 %", "100 %", "200 %", "300 %"], 2),
                ("Um wie viel verbessert die Gedächtnispalast-Technik den Abruf?",
                 ["40 %", "60 %", "80 %", "100 %"], 2),
            ],
        ),
        (
            "Bewegung und das Gehirn",
            [
                "30 Min Aerobic erhöht BDNF um 32 %",
                "Regelmäßige Bewegung vergrößert den Hippocampus um 2 %",
                "Bewegung verbessert die exekutiven Funktionen um 20 %",
                "Optimale kognitive Vorteile: 150 Min moderate Bewegung/Woche",
                "Bewegung nach dem Lernen verbessert das Behalten um 10 %",
                "Körperliche Fitness reduziert das Demenzrisiko um 30 %",
            ],
            [
                ("Um wie viel erhöht 30 Min Aerobic den BDNF?",
                 ["12 %", "22 %", "32 %", "42 %"], 2),
                ("Um wie viel vergrößert Bewegung den Hippocampus?",
                 ["0,5 %", "1 %", "2 %", "4 %"], 2),
                ("Wie viel moderate Bewegung pro Woche ist optimal?",
                 ["60 Min", "90 Min", "150 Min", "200 Min"], 2),
            ],
        ),
        (
            "Meditation und neuronale Veränderungen",
            [
                "8 Wochen Meditation erhöhen die Dichte der grauen Substanz",
                "Meditierende zeigen 25 % mehr Aktivität im präfrontalen Kortex",
                "Achtsamkeit reduziert das Amygdala-Volumen um 5 %",
                "Langzeit-Meditierende: 50 % mehr Gamma-Wellen-Aktivität",
                "Meditation verbessert die Aufmerksamkeitsspanne um 14 %",
                "Tägliche Praxis von 12 Min zeigt messbare Gehirnveränderungen",
            ],
            [
                ("Wie viel mehr präfrontale Aktivität zeigen Meditierende?",
                 ["10 %", "15 %", "25 %", "35 %"], 2),
                ("Um wie viel reduziert Achtsamkeit das Amygdala-Volumen?",
                 ["2 %", "5 %", "8 %", "12 %"], 1),
                ("Wie viele Minuten tägliche Meditation zeigen messbare Effekte?",
                 ["5 Min", "8 Min", "12 Min", "20 Min"], 2),
            ],
        ),
        (
            "Zweisprachigkeit und Kognition",
            [
                "Zweisprachige wechseln 4,5 Mal schneller zwischen Aufgaben",
                "Demenz-Beginn verzögert sich um 4–5 Jahre bei Zweisprachigen",
                "Zweisprachige Gehirne haben dichtere graue Substanz im ACC",
                "Exekutive Kontrolle: 15 % besser bei Zweisprachigen",
                "Kritische Phase für Spracherwerb: vor dem 7. Lebensjahr",
                "Zweisprachige zeigen überlegene Arbeitsgedächtnis-Kapazität",
            ],
            [
                ("Wie viel schneller wechseln Zweisprachige zwischen Aufgaben?",
                 ["2,5×", "3,5×", "4,5×", "5,5×"], 2),
                ("Um wie viele Jahre verzögert Zweisprachigkeit den Demenz-Beginn?",
                 ["1–2 Jahre", "2–3 Jahre", "4–5 Jahre", "6–7 Jahre"], 2),
                ("Bis zu welchem Alter ist die kritische Phase für Sprachen?",
                 ["5 Jahre", "7 Jahre", "10 Jahre", "12 Jahre"], 1),
            ],
        ),
    ],
    "humor": [
        (
            "Wissenschaft des Lachens",
            [
                "Durchschnittlicher Erwachsener lacht 17 Mal am Tag",
                "Lachen verbrennt 10–40 Kalorien in 15 Minuten",
                "Babys beginnen mit etwa 4 Monaten zu lachen",
                "Lachen setzt Endorphine frei und reduziert Cortisol um 39 %",
                "Gelotologie: die wissenschaftliche Erforschung des Lachens",
                "Lachen ist ansteckend — 30× wahrscheinlicher in Gruppen",
            ],
            [
                ("Wie oft lacht ein Erwachsener durchschnittlich am Tag?",
                 ["7 Mal", "12 Mal", "17 Mal", "25 Mal"], 2),
                ("Um wie viel reduziert Lachen das Cortisol?",
                 ["19 %", "29 %", "39 %", "49 %"], 2),
                ("Wie heißt die Wissenschaft des Lachens?",
                 ["Humorologie", "Gelotologie", "Risologie", "Komikologie"], 1),
            ],
        ),
        (
            "Kuriose Tierfakten",
            [
                "Oktopusse haben 3 Herzen und blaues Blut",
                "Ein Kolibri wiegt weniger als ein 5-Cent-Stück",
                "Kühe haben beste Freunde und werden gestresst ohne sie",
                "Delfine schlafen mit einem offenen Auge",
                "Flamingos sind nur rosa wegen ihrer Ernährung mit Garnelen",
                "Faultiere brauchen 2 Wochen um Nahrung zu verdauen",
            ],
            [
                ("Wie viele Herzen hat ein Oktopus?",
                 ["1", "2", "3", "4"], 2),
                ("Warum sind Flamingos rosa?",
                 ["Genetik", "Sonnenlicht", "Garnelen-Ernährung", "Wasserchemie"], 2),
                ("Wie lange brauchen Faultiere zur Verdauung?",
                 ["3 Tage", "1 Woche", "2 Wochen", "1 Monat"], 2),
            ],
        ),
        (
            "Absurde Weltrekorde",
            [
                "Längster Schluckauf: 68 Jahre (Charles Osborne)",
                "Meiste T-Shirts gleichzeitig getragen: 260",
                "Schnellstes Rückwärtslaufen: 100 m in 13,6 Sekunden",
                "Längster Fingernagel je: 8,65 Meter (Einzelnagel)",
                "Meiste Hotdogs in 10 Min gegessen: 76",
                "Lautestes Schnarchen gemessen: 93 Dezibel",
            ],
            [
                ("Wie lange dauerte der längste Schluckauf?",
                 ["12 Jahre", "34 Jahre", "68 Jahre", "85 Jahre"], 2),
                ("Wie viele T-Shirts wurden gleichzeitig getragen?",
                 ["120", "185", "260", "340"], 2),
                ("Wie laut war das lauteste gemessene Schnarchen?",
                 ["73 dB", "83 dB", "93 dB", "103 dB"], 2),
            ],
        ),
        (
            "Kurioses über Essen",
            [
                "Honig verdirbt nie — 3.000 Jahre alter Honig war noch essbar",
                "Bananen sind botanisch gesehen Beeren, Erdbeeren nicht",
                "Ketchup wurde in den 1830ern als Medizin verkauft",
                "Durchschnittlicher Mensch isst 35 Tonnen Nahrung im Leben",
                "Wasabi in Restaurants ist meist gefärbter Meerrettich",
                "Ananas braucht 2–3 Jahre um zu wachsen",
            ],
            [
                ("Wie alt war der älteste noch essbare Honig?",
                 ["500 Jahre", "1.000 Jahre", "3.000 Jahre", "5.000 Jahre"], 2),
                ("Wie viel Nahrung isst ein Mensch durchschnittlich im Leben?",
                 ["15 Tonnen", "25 Tonnen", "35 Tonnen", "50 Tonnen"], 2),
                ("Wie lange braucht eine Ananas zum Wachsen?",
                 ["6 Monate", "1 Jahr", "2–3 Jahre", "5 Jahre"], 2),
            ],
        ),
        (
            "Nutzlos aber wahr",
            [
                "Ein Blitz ist 5× heißer als die Sonnenoberfläche",
                "Die Erde dreht sich mit 1.670 km/h am Äquator",
                "Menschliche Knochen sind stärker als Stahl (gewichtsbezogen)",
                "Es gibt mehr Sterne im Universum als Sandkörner auf der Erde",
                "Dein Magen bekommt alle 3–4 Tage eine neue Schleimhaut",
                "Oxford University ist älter als das Azteken-Reich",
            ],
            [
                ("Wie viel heißer ist ein Blitz als die Sonnenoberfläche?",
                 ["2×", "3×", "5×", "8×"], 2),
                ("Wie schnell dreht sich die Erde am Äquator?",
                 ["670 km/h", "1.070 km/h", "1.670 km/h", "2.270 km/h"], 2),
                ("Wie oft erneuert sich die Magenschleimhaut?",
                 ["Alle 1–2 Tage", "Alle 3–4 Tage", "Alle 7 Tage", "Alle 14 Tage"], 1),
            ],
        ),
    ],
    "history": [
        (
            "Das Antike Rom",
            [
                "Gründung: 753 v. Chr. (der Legende nach)",
                "Maximale Bevölkerung: 1 Million (1. Jh. n. Chr.)",
                "Straßennetz: 400.000 km im gesamten Reich",
                "Kolosseum fasste 50.000–80.000 Zuschauer",
                "Aquädukte transportierten 1 Million m³ Wasser täglich",
                "Das Reich bestand 1.000+ Jahre (753 v. Chr. – 476 n. Chr.)",
            ],
            [
                ("Wann wurde Rom der Legende nach gegründet?",
                 ["509 v. Chr.", "753 v. Chr.", "264 v. Chr.", "1.000 v. Chr."], 1),
                ("Wie viele Zuschauer fasste das Kolosseum?",
                 ["20.000–30.000", "35.000–45.000", "50.000–80.000", "90.000–100.000"], 2),
                ("Wie lang war das römische Straßennetz?",
                 ["100.000 km", "250.000 km", "400.000 km", "600.000 km"], 2),
            ],
        ),
        (
            "Die Mondlandung",
            [
                "Datum: 20. Juli 1969 (Apollo 11)",
                "Erste Worte auf dem Mond: Neil Armstrong",
                "Missionsdauer: 8 Tage 3 Stunden 18 Minuten",
                "Entfernung Erde–Mond: 384.400 km",
                "Mondgestein mitgebracht: 21,55 kg",
                "Geschätzte Kosten: 25,4 Milliarden $ (1973-Dollar)",
            ],
            [
                ("Wann war die erste Mondlandung?",
                 ["15. März 1968", "20. Juli 1969", "12. April 1970", "3. Juni 1971"], 1),
                ("Wie viel Mondgestein wurde mitgebracht?",
                 ["8,2 kg", "15,3 kg", "21,55 kg", "34,7 kg"], 2),
                ("Wie weit ist der Mond von der Erde entfernt?",
                 ["284.400 km", "384.400 km", "484.400 km", "584.400 km"], 1),
            ],
        ),
        (
            "Zweiter Weltkrieg — Schlüsselzahlen",
            [
                "Dauer: 1939–1945 (6 Jahre)",
                "Beteiligte Nationen: über 30",
                "Geschätzte Gesamtopfer: 70–85 Millionen",
                "D-Day: 6. Juni 1944 — 156.000 alliierte Soldaten",
                "Kosten: geschätzt 1,657 Billionen $ (1945-Dollar)",
                "Ende in Europa: 8. Mai 1945 (V-E Day)",
            ],
            [
                ("Wie viele Nationen waren am 2. Weltkrieg beteiligt?",
                 ["Über 10", "Über 20", "Über 30", "Über 50"], 2),
                ("Wie viele alliierte Soldaten landeten am D-Day?",
                 ["75.000", "120.000", "156.000", "200.000"], 2),
                ("Wann endete der Krieg in Europa?",
                 ["8. Mai 1945", "2. September 1945", "15. August 1945", "11. November 1944"], 0),
            ],
        ),
        (
            "Die Renaissance",
            [
                "Zeitraum: ca. 1350–1600 n. Chr.",
                "Ursprung: Florenz, Italien",
                "Leonardo da Vinci malte die Mona Lisa ca. 1503–1519",
                "Gutenbergs Druckerpresse: ca. 1440",
                "Michelangelos Decke der Sixtinischen Kapelle: 1508–1512",
                "Bevölkerung Europas: ~60 Millionen nach der Pest",
            ],
            [
                ("Wo begann die Renaissance?",
                 ["Paris", "Rom", "Florenz", "Venedig"], 2),
                ("Wann erfand Gutenberg die Druckerpresse?",
                 ["ca. 1380", "ca. 1440", "ca. 1500", "ca. 1550"], 1),
                ("Wie lange malte Michelangelo die Sixtinische Decke?",
                 ["1 Jahr", "2 Jahre", "4 Jahre", "8 Jahre"], 2),
            ],
        ),
        (
            "Die Industrielle Revolution",
            [
                "Beginn: ca. 1760 in Großbritannien",
                "Watts Dampfmaschine: patentiert 1769",
                "Erste Eisenbahn: Stockton–Darlington 1825",
                "Stadtbevölkerung wuchs von 20 % auf 50 % bis 1850",
                "Kinderarbeit: Kinder ab 5 Jahren arbeiteten 16-Stunden-Schichten",
                "Baumwollproduktion stieg um 800 % zwischen 1770 und 1800",
            ],
            [
                ("Wo begann die Industrielle Revolution?",
                 ["Frankreich", "Deutschland", "Großbritannien", "USA"], 2),
                ("Wann wurde Watts Dampfmaschine patentiert?",
                 ["1745", "1769", "1785", "1801"], 1),
                ("Um wie viel stieg die Baumwollproduktion 1770–1800?",
                 ["200 %", "400 %", "800 %", "1.200 %"], 2),
            ],
        ),
    ],
    "nutrition": [
        (
            "Makronährstoffe",
            [
                "Kohlenhydrate: 4 Kalorien pro Gramm",
                "Proteine: 4 Kalorien pro Gramm",
                "Fette: 9 Kalorien pro Gramm",
                "Empfohlene Verteilung: 45–65 % Kohlenhydrate, 20–35 % Fett, 10–35 % Protein",
                "Ballaststoffe: 25–30 g pro Tag empfohlen",
                "Durchschnittlicher Erwachsener braucht 2.000–2.500 kcal/Tag",
            ],
            [
                ("Wie viele Kalorien hat ein Gramm Fett?",
                 ["4", "7", "9", "12"], 2),
                ("Wie viel Ballaststoffe pro Tag werden empfohlen?",
                 ["10–15 g", "15–20 g", "25–30 g", "35–40 g"], 2),
                ("Wie viel Prozent der Kalorien sollten aus Kohlenhydraten kommen?",
                 ["25–40 %", "45–65 %", "60–80 %", "70–90 %"], 1),
            ],
        ),
        (
            "Fakten zur Hydratation",
            [
                "Menschlicher Körper: 60 % Wasser",
                "Gehirn und Herz: 73 % Wasser",
                "Empfohlene Aufnahme: 2,7–3,7 Liter/Tag (inkl. Nahrung)",
                "2 % Dehydrierung reduziert kognitive Leistung um 25 %",
                "Nieren filtern 180 Liter Blut täglich",
                "Koffein ist ein mildes Diuretikum — Nettoeffekt ist minimal",
            ],
            [
                ("Wie viel Prozent des Körpers ist Wasser?",
                 ["45 %", "52 %", "60 %", "70 %"], 2),
                ("Um wie viel reduziert 2 % Dehydrierung die kognitive Leistung?",
                 ["10 %", "15 %", "25 %", "35 %"], 2),
                ("Wie viel Blut filtern die Nieren täglich?",
                 ["90 Liter", "120 Liter", "180 Liter", "240 Liter"], 2),
            ],
        ),
        (
            "Vitamine und Mineralstoffe",
            [
                "Vitamin D: 1 Milliarde Menschen weltweit haben Mangel",
                "Eisen: 25 % der Weltbevölkerung hat Eisenmangel",
                "Vitamin C: 90 mg/Tag empfohlen für Erwachsene",
                "Kalzium: 99 % ist in Knochen und Zähnen gespeichert",
                "B12: nur in tierischen Produkten natürlich vorhanden",
                "Zink: unterstützt 300+ enzymatische Reaktionen",
            ],
            [
                ("Wie viele Menschen haben weltweit Vitamin-D-Mangel?",
                 ["100 Millionen", "500 Millionen", "1 Milliarde", "2 Milliarden"], 2),
                ("Wie viel Vitamin C pro Tag wird empfohlen?",
                 ["45 mg", "60 mg", "90 mg", "120 mg"], 2),
                ("Wie viel Prozent des Kalziums ist in Knochen und Zähnen?",
                 ["85 %", "92 %", "99 %", "100 %"], 2),
            ],
        ),
        (
            "Darm-Hirn-Verbindung",
            [
                "Der Darm enthält 500 Millionen Neuronen",
                "95 % des Serotonins wird im Darm produziert",
                "Darmmikrobiom: 100 Billionen Bakterien",
                "Vagusnerv: direkte Verbindung zwischen Darm und Gehirn",
                "Darmgesundheit beeinflusst Stimmung, Schlaf und Kognition",
                "Probiotika können Angstsymptome um 20 % reduzieren",
            ],
            [
                ("Wie viele Neuronen enthält der Darm?",
                 ["100 Millionen", "300 Millionen", "500 Millionen", "800 Millionen"], 2),
                ("Wie viel Prozent des Serotonins wird im Darm produziert?",
                 ["50 %", "75 %", "85 %", "95 %"], 3),
                ("Um wie viel können Probiotika Angstsymptome reduzieren?",
                 ["10 %", "15 %", "20 %", "30 %"], 2),
            ],
        ),
        (
            "Koffein und Leistung",
            [
                "Koffein blockiert Adenosin-Rezeptoren im Gehirn",
                "Wirkungseintritt: 15–45 Minuten nach Einnahme",
                "Halbwertszeit: 5–6 Stunden im Durchschnitt",
                "Optimale Dosis: 3–6 mg/kg Körpergewicht",
                "Verbessert die Reaktionszeit um 11 %",
                "Sichere Tagesdosis: bis zu 400 mg (ca. 4 Tassen Kaffee)",
            ],
            [
                ("Wie lange dauert es, bis Koffein wirkt?",
                 ["5–10 Min", "15–45 Min", "60–90 Min", "2–3 Stunden"], 1),
                ("Um wie viel verbessert Koffein die Reaktionszeit?",
                 ["5 %", "8 %", "11 %", "15 %"], 2),
                ("Wie viel Koffein pro Tag gilt als sicher?",
                 ["200 mg", "300 mg", "400 mg", "500 mg"], 2),
            ],
        ),
    ],
}
