"""Italian slide library for Slide Processing exercise."""

SLIDE_LIBRARY = {
    "science": [
        (
            "Il cervello umano",
            [
                "Peso: 1,4 kg (circa il 2 % del peso corporeo)",
                "Contiene circa 86 miliardi di neuroni",
                "Usa il 20 % dell'energia totale del corpo",
                "Genera circa 23 watt di potenza elettrica",
                "Velocità di elaborazione: fino a 120 m/s",
                "Capacità di archiviazione stimata in 2,5 petabyte",
            ],
            [
                ("Quanti neuroni contiene il cervello?",
                 ["12 miliardi", "86 miliardi", "100 miliardi", "45 miliardi"], 1),
                ("Quale percentuale di energia corporea usa il cervello?",
                 ["10 %", "15 %", "20 %", "30 %"], 2),
                ("Qual è la capacità di archiviazione stimata?",
                 ["1,5 petabyte", "2,5 petabyte", "5 petabyte", "500 terabyte"], 1),
            ],
        ),
        (
            "Esplorazione di Marte",
            [
                "Distanza dalla Terra: da 54,6 a 401 milioni di km",
                "Temperatura superficiale: da −87 °C a −5 °C in media",
                "Olympus Mons: vulcano più alto con 21,9 km",
                "Durata del giorno (sol): 24 ore 37 minuti",
                "Atmosfera: 95,3 % di anidride carbonica",
                "Gravità: 3,72 m/s² (38 % di quella terrestre)",
            ],
            [
                ("Qual è l'altezza dell'Olympus Mons?",
                 ["15,2 km", "18,6 km", "21,9 km", "25,1 km"], 2),
                ("Quale percentuale dell'atmosfera di Marte è CO₂?",
                 ["78,1 %", "89,7 %", "95,3 %", "99,2 %"], 2),
                ("Qual è la gravità di Marte rispetto alla Terra?",
                 ["28 %", "38 %", "48 %", "58 %"], 1),
            ],
        ),
        (
            "Fatti sugli oceani",
            [
                "Gli oceani coprono il 71 % della superficie terrestre",
                "Profondità media: 3.688 metri",
                "Punto più profondo: Fossa delle Marianne a 10.994 m",
                "Contiene il 97 % dell'acqua della Terra",
                "Oceano Pacifico: il più grande con 165,25 milioni di km²",
                "Temperatura dell'acqua: da −2 °C a 36 °C",
            ],
            [
                ("Qual è la profondità media degli oceani?",
                 ["2.450 m", "3.688 m", "4.200 m", "5.100 m"], 1),
                ("Quale percentuale dell'acqua terrestre è negli oceani?",
                 ["87 %", "92 %", "97 %", "99 %"], 2),
                ("Quanto è profonda la Fossa delle Marianne?",
                 ["8.848 m", "9.500 m", "10.994 m", "12.100 m"], 2),
            ],
        ),
        (
            "La velocità della luce",
            [
                "Velocità nel vuoto: 299.792.458 m/s",
                "La luce percorre 9.461 miliardi di km all'anno",
                "La luce solare raggiunge la Terra in 8 min 20 s",
                "Luce dalla Luna: 1,3 secondi fino alla Terra",
                "Stella più vicina (Proxima Centauri): 4,24 anni luce",
                "La luce rallenta a 225.000 km/s nell'acqua",
            ],
            [
                ("Quanto impiega la luce solare a raggiungere la Terra?",
                 ["4 min 10 s", "6 min 45 s", "8 min 20 s", "12 min 5 s"], 2),
                ("A che distanza è Proxima Centauri in anni luce?",
                 ["2,18", "4,24", "6,71", "8,60"], 1),
                ("Qual è la velocità della luce nell'acqua?",
                 ["150.000 km/s", "225.000 km/s", "275.000 km/s", "299.792 km/s"], 1),
            ],
        ),
        (
            "DNA e genetica",
            [
                "Genoma umano: 3,2 miliardi di coppie di basi",
                "Gli umani condividono il 98,7 % del DNA con gli scimpanzé",
                "Ogni cellula contiene circa 2 metri di DNA",
                "Solo l'1,5 % del DNA codifica proteine",
                "23 coppie di cromosomi nelle cellule umane",
                "Velocità di replicazione del DNA: 1.000 nucleotidi/secondo",
            ],
            [
                ("Quante coppie di basi ha il genoma umano?",
                 ["1,8 miliardi", "3,2 miliardi", "4,6 miliardi", "6,4 miliardi"], 1),
                ("Quale percentuale del DNA codifica proteine?",
                 ["1,5 %", "5 %", "10 %", "25 %"], 0),
                ("Quanto DNA contiene ogni cellula?",
                 ["0,5 metri", "2 metri", "5 metri", "10 metri"], 1),
            ],
        ),
    ],
    "business": [
        (
            "Mercato globale del caffè 2024",
            [
                "Valore di mercato: 495,2 miliardi di dollari",
                "Consumo annuale: 10,5 miliardi di kg nel mondo",
                "Maggior produttore: Brasile (37,4 % della produzione mondiale)",
                "Prezzo medio al kg: 14,80 $ (arabica)",
                "Segmento caffè speciale in crescita del 12,3 % CAGR",
                "La Finlandia guida il consumo pro capite: 12 kg/anno",
            ],
            [
                ("Qual è il valore del mercato globale del caffè?",
                 ["312,8 Mld $", "495,2 Mld $", "620,5 Mld $", "780,1 Mld $"], 1),
                ("Quale percentuale del caffè mondiale produce il Brasile?",
                 ["22,1 %", "29,8 %", "37,4 %", "45,6 %"], 2),
                ("Quale paese guida il consumo di caffè pro capite?",
                 ["Italia", "Colombia", "Finlandia", "USA"], 2),
            ],
        ),
        (
            "Vendite di veicoli elettrici",
            [
                "Vendite globali di VE 2024: 17,1 milioni di unità",
                "Quota di mercato: 22 % di tutte le vendite di auto nuove",
                "La Cina guida con il 59 % delle vendite globali di VE",
                "Costo medio batteria VE: 139 $/kWh",
                "Quota di mercato Tesla: 18,4 % dei VE globali",
                "Autonomia media VE: 348 km per carica",
            ],
            [
                ("Quanti VE sono stati venduti nel mondo nel 2024?",
                 ["9,8 milioni", "13,5 milioni", "17,1 milioni", "21,4 milioni"], 2),
                ("Qual è la quota della Cina nelle vendite globali di VE?",
                 ["35 %", "47 %", "59 %", "72 %"], 2),
                ("Qual è il costo medio della batteria VE per kWh?",
                 ["89 $", "139 $", "189 $", "239 $"], 1),
            ],
        ),
        (
            "Statistiche sul lavoro da remoto",
            [
                "32,6 milioni di americani lavoreranno da remoto nel 2025",
                "Aumento di produttività: 13 % per i lavoratori da remoto",
                "Tempo di pendolarismo risparmiato: 72 minuti/giorno",
                "Le aziende risparmiano 11.000 $ per lavoratore remoto/anno",
                "Il 67 % riporta un migliore equilibrio vita-lavoro",
                "Mercato videoconferenze: 13,8 miliardi di dollari",
            ],
            [
                ("Quanto tempo di pendolarismo risparmiano i lavoratori remoti?",
                 ["45 minuti", "72 minuti", "90 minuti", "120 minuti"], 1),
                ("Quanto risparmiano le aziende per lavoratore remoto?",
                 ["5.000 $", "8.500 $", "11.000 $", "15.000 $"], 2),
                ("Qual è l'aumento di produttività nel lavoro da remoto?",
                 ["8 %", "13 %", "18 %", "25 %"], 1),
            ],
        ),
        (
            "Mercato smartphone Q4 2024",
            [
                "Spedizioni globali: 328,2 milioni di unità",
                "Samsung: 19,4 % di quota di mercato (n. 1)",
                "Apple: 18,2 % di quota di mercato (n. 2)",
                "Prezzo medio di vendita: 322 $",
                "Telefoni 5G: 78 % di tutte le spedizioni",
                "Telefoni pieghevoli cresciuti del 49 % su base annua",
            ],
            [
                ("Quanti smartphone spediti nel Q4 2024?",
                 ["245,6 milioni", "328,2 milioni", "412,7 milioni", "501,3 milioni"], 1),
                ("Qual era la quota di mercato di Samsung?",
                 ["15,8 %", "19,4 %", "23,1 %", "27,6 %"], 1),
                ("Quale percentuale delle spedizioni erano telefoni 5G?",
                 ["58 %", "68 %", "78 %", "88 %"], 2),
            ],
        ),
        (
            "Turismo mondiale 2024",
            [
                "Arrivi internazionali: 1,4 miliardi",
                "Entrate turistiche: 1.900 miliardi di dollari",
                "Paese più visitato: Francia (100 milioni di visitatori)",
                "Spesa media per turista: 1.350 $",
                "Il turismo impiega 330 milioni di persone nel mondo",
                "Crescita Asia-Pacifico: 18 % su base annua",
            ],
            [
                ("Quanti arrivi turistici internazionali nel 2024?",
                 ["0,8 miliardi", "1,1 miliardi", "1,4 miliardi", "1,8 miliardi"], 2),
                ("Quale paese ha avuto più visitatori?",
                 ["Spagna", "USA", "Francia", "Italia"], 2),
                ("Quante persone impiega il turismo nel mondo?",
                 ["180 milioni", "250 milioni", "330 milioni", "420 milioni"], 2),
            ],
        ),
    ],
    "geography": [
        (
            "Giappone",
            [
                "Popolazione: 123,3 milioni (2024)",
                "Capitale: Tokyo (13,96 milioni di abitanti)",
                "Superficie: 377.975 km²",
                "Punto più alto: Monte Fuji a 3.776 metri",
                "PIL pro capite: 33.950 $",
                "Aspettativa di vita: 84,8 anni (la più alta al mondo)",
            ],
            [
                ("Qual è la popolazione del Giappone?",
                 ["98,5 milioni", "123,3 milioni", "145,7 milioni", "168,2 milioni"], 1),
                ("Quanto è alto il Monte Fuji?",
                 ["2.954 m", "3.776 m", "4.421 m", "5.108 m"], 1),
                ("Qual è l'aspettativa di vita in Giappone?",
                 ["78,2 anni", "81,5 anni", "84,8 anni", "87,3 anni"], 2),
            ],
        ),
        (
            "Brasile",
            [
                "Popolazione: 216,4 milioni (2024)",
                "Capitale: Brasilia (non São Paulo né Rio)",
                "Superficie: 8.515.767 km² (5° paese più grande)",
                "Foresta amazzonica: 5,5 milioni di km²",
                "Lingua ufficiale: portoghese",
                "Costa: 7.491 km di lunghezza",
            ],
            [
                ("Qual è la capitale del Brasile?",
                 ["São Paulo", "Rio de Janeiro", "Brasilia", "Salvador"], 2),
                ("Quanto è grande la foresta amazzonica?",
                 ["3,2 M km²", "5,5 M km²", "7,8 M km²", "9,1 M km²"], 1),
                ("Quanto è lunga la costa del Brasile?",
                 ["4.230 km", "5.860 km", "7.491 km", "9.120 km"], 2),
            ],
        ),
        (
            "Australia",
            [
                "Popolazione: 26,6 milioni (2024)",
                "Capitale: Canberra (non Sydney)",
                "Superficie: 7.692.024 km² (6° paese più grande)",
                "Grande Barriera Corallina: 2.300 km di lunghezza",
                "Punto più alto: Monte Kosciuszko a 2.228 m",
                "L'87 % della popolazione vive in aree urbane",
            ],
            [
                ("Qual è la popolazione dell'Australia?",
                 ["18,4 milioni", "26,6 milioni", "34,2 milioni", "42,8 milioni"], 1),
                ("Quanto è lunga la Grande Barriera Corallina?",
                 ["1.200 km", "1.800 km", "2.300 km", "2.900 km"], 2),
                ("Quale percentuale di australiani vive in aree urbane?",
                 ["72 %", "79 %", "87 %", "94 %"], 2),
            ],
        ),
        (
            "Svizzera",
            [
                "Popolazione: 8,9 milioni (2024)",
                "Capitale: Berna (non Zurigo né Ginevra)",
                "4 lingue ufficiali: tedesco, francese, italiano, romancio",
                "Superficie: 41.285 km²",
                "Punto più alto: Punta Dufour a 4.634 m",
                "PIL pro capite: 99.994 $ (2° più alto al mondo)",
            ],
            [
                ("Qual è la capitale della Svizzera?",
                 ["Zurigo", "Ginevra", "Berna", "Basilea"], 2),
                ("Quante lingue ufficiali ha la Svizzera?",
                 ["2", "3", "4", "5"], 2),
                ("Qual è il PIL pro capite della Svizzera?",
                 ["67.450 $", "82.310 $", "99.994 $", "115.200 $"], 2),
            ],
        ),
        (
            "Egitto",
            [
                "Popolazione: 109,3 milioni (2024)",
                "Capitale: Il Cairo (21,9 milioni di abitanti)",
                "Fiume Nilo: 6.650 km (il più lungo d'Africa)",
                "Grande Piramide: 146,6 metri di altezza (originariamente)",
                "Superficie: 1.002.450 km² (97 % deserto)",
                "Canale di Suez: 193,3 km di lunghezza, aperto nel 1869",
            ],
            [
                ("Qual è la popolazione del Cairo?",
                 ["14,2 milioni", "17,5 milioni", "21,9 milioni", "25,3 milioni"], 2),
                ("Quanto è lungo il Nilo?",
                 ["4.130 km", "5.390 km", "6.650 km", "7.920 km"], 2),
                ("Quanto è lungo il Canale di Suez?",
                 ["120,5 km", "156,8 km", "193,3 km", "231,7 km"], 2),
            ],
        ),
    ],
    "motivation": [
        (
            "La regola delle 10.000 ore",
            [
                "Resa popolare da Malcolm Gladwell in Outliers (2008)",
                "Basata sulla ricerca di K. Anders Ericsson",
                "I violinisti d'élite avevano 10.000 ore di pratica a 20 anni",
                "La pratica deliberata conta più delle ore totali",
                "I migliori praticano 4 ore/giorno con piena concentrazione",
                "I cicli di feedback accelerano l'apprendimento del 26 %",
            ],
            [
                ("Chi ha reso popolare la regola delle 10.000 ore?",
                 ["Daniel Kahneman", "Malcolm Gladwell", "Cal Newport", "James Clear"], 1),
                ("Quante ore/giorno praticano i migliori?",
                 ["2 ore", "4 ore", "6 ore", "8 ore"], 1),
                ("Di quanto i cicli di feedback accelerano l'apprendimento?",
                 ["12 %", "18 %", "26 %", "35 %"], 2),
            ],
        ),
        (
            "Ricerca sulla mentalità di crescita",
            [
                "Coniato da Carol Dweck alla Stanford University",
                "Gli studenti lodati per l'impegno sono migliorati del 30 % in più",
                "Mentalità fissa: l'intelligenza è statica",
                "Mentalità di crescita: le capacità si sviluppano con la dedizione",
                "Il 73 % dei top CEO si identifica con la mentalità di crescita",
                "Gli interventi sulla mentalità hanno alzato le medie di 0,3 punti",
            ],
            [
                ("Chi ha coniato il termine 'mentalità di crescita'?",
                 ["Angela Duckworth", "Carol Dweck", "Martin Seligman", "Amy Cuddy"], 1),
                ("Di quanto sono migliorati gli studenti lodati per l'impegno?",
                 ["10 %", "20 %", "30 %", "40 %"], 2),
                ("Quale percentuale dei top CEO ha una mentalità di crescita?",
                 ["53 %", "63 %", "73 %", "83 %"], 2),
            ],
        ),
        (
            "Il potere delle abitudini",
            [
                "Il 40 % delle azioni quotidiane sono abitudini",
                "Ciclo dell'abitudine: segnale → routine → ricompensa (Duhigg)",
                "Formare una nuova abitudine richiede in media 66 giorni",
                "Le intenzioni di implementazione aumentano il successo del 91 %",
                "Le abitudini chiave innescano cambiamenti positivi a cascata",
                "Impilamento di abitudini: collegare le nuove alle esistenti",
            ],
            [
                ("Quale percentuale delle azioni quotidiane sono abitudini?",
                 ["20 %", "30 %", "40 %", "50 %"], 2),
                ("Quanti giorni servono per formare una nuova abitudine?",
                 ["21 giorni", "45 giorni", "66 giorni", "90 giorni"], 2),
                ("Di quanto le intenzioni di implementazione aumentano il successo?",
                 ["51 %", "71 %", "81 %", "91 %"], 3),
            ],
        ),
        (
            "Stato di flow e prestazione",
            [
                "Concetto sviluppato da Mihaly Csikszentmihalyi nel 1975",
                "Il flow aumenta la produttività fino al 500 %",
                "Richiede equilibrio sfida-competenza (4 % sopra il livello attuale)",
                "Tempo medio per entrare in flow: 15–20 minuti",
                "Le interruzioni azzerano completamente il timer del flow",
                "Il flow attiva 5 neurochimici: dopamina, noradrenalina, endorfine, anandamide, serotonina",
            ],
            [
                ("Chi ha sviluppato il concetto di flow?",
                 ["Daniel Pink", "Mihaly Csikszentmihalyi", "Cal Newport", "Adam Grant"], 1),
                ("Di quanto il flow può aumentare la produttività?",
                 ["100 %", "200 %", "350 %", "500 %"], 3),
                ("Quanto tempo serve per entrare in flow?",
                 ["5–10 minuti", "15–20 minuti", "25–30 minuti", "35–40 minuti"], 1),
            ],
        ),
        (
            "Grinta e perseveranza",
            [
                "Ricercata da Angela Duckworth alla UPenn",
                "La grinta predice il successo meglio del QI nel 78 % degli studi",
                "Cadetti di West Point: il punteggio di grinta prediceva il tasso di completamento",
                "Grinta = passione + persistenza sostenuta negli anni",
                "Le persone con grinta praticano il 32 % di ore in più a settimana",
                "La grinta può essere sviluppata — non è puramente innata",
            ],
            [
                ("Chi ha ricercato la grinta?",
                 ["Carol Dweck", "Angela Duckworth", "Martin Seligman", "Dan Pink"], 1),
                ("In quale percentuale di studi la grinta supera il QI?",
                 ["58 %", "68 %", "78 %", "88 %"], 2),
                ("Quanto di più praticano le persone con grinta a settimana?",
                 ["12 %", "22 %", "32 %", "42 %"], 2),
            ],
        ),
    ],
    "neuroplasticity": [
        (
            "Basi della neuroplasticità",
            [
                "Il cervello forma 1 milione di nuove connessioni/secondo nell'infanzia",
                "Gli adulti generano ~700 nuovi neuroni/giorno nell'ippocampo",
                "I tassisti di Londra hanno ippocampi posteriori il 16 % più grandi",
                "La neuroplasticità raggiunge il picco prima dei 25 anni",
                "Imparare una nuova abilità aumenta la materia grigia in 2 settimane",
                "Il sonno consolida i percorsi neurali — 7–9 ore ottimali",
            ],
            [
                ("Quanti nuovi neuroni generano gli adulti al giorno?",
                 ["200", "500", "700", "1.000"], 2),
                ("Di quanto sono più grandi gli ippocampi dei tassisti?",
                 ["8 %", "12 %", "16 %", "22 %"], 2),
                ("In quanto tempo l'apprendimento aumenta la materia grigia?",
                 ["2 giorni", "2 settimane", "2 mesi", "6 mesi"], 1),
            ],
        ),
        (
            "Formazione della memoria",
            [
                "La memoria a breve termine dura 15–30 secondi senza ripetizione",
                "Capacità della memoria di lavoro: 4 ± 1 elementi",
                "Consolidamento: l'ippocampo trasferisce alla neocorteccia nel sonno",
                "La ripetizione spaziata migliora la ritenzione del 200 %",
                "I ricordi emotivi sono 3× più forti (coinvolgimento dell'amigdala)",
                "La tecnica del palazzo della memoria migliora il richiamo dell'80 %",
            ],
            [
                ("Quanto dura la memoria a breve termine senza ripetizione?",
                 ["5–10 s", "15–30 s", "45–60 s", "2–3 min"], 1),
                ("Di quanto la ripetizione spaziata migliora la ritenzione?",
                 ["50 %", "100 %", "200 %", "300 %"], 2),
                ("Di quanto il palazzo della memoria migliora il richiamo?",
                 ["40 %", "60 %", "80 %", "100 %"], 2),
            ],
        ),
        (
            "Esercizio e cervello",
            [
                "30 min di aerobica aumentano il BDNF del 32 %",
                "L'esercizio regolare ingrandisce l'ippocampo del 2 %",
                "L'esercizio migliora le funzioni esecutive del 20 %",
                "Benefici cognitivi ottimali: 150 min di esercizio moderato/settimana",
                "L'esercizio dopo lo studio migliora la ritenzione del 10 %",
                "La forma fisica riduce il rischio di demenza del 30 %",
            ],
            [
                ("Di quanto 30 min di aerobica aumentano il BDNF?",
                 ["12 %", "22 %", "32 %", "42 %"], 2),
                ("Di quanto l'esercizio ingrandisce l'ippocampo?",
                 ["0,5 %", "1 %", "2 %", "4 %"], 2),
                ("Quanti minuti di esercizio moderato a settimana sono ottimali?",
                 ["60 min", "90 min", "150 min", "200 min"], 2),
            ],
        ),
        (
            "Meditazione e cambiamenti neurali",
            [
                "8 settimane di meditazione aumentano la densità di materia grigia",
                "I meditatori mostrano il 25 % in più di attività nella corteccia prefrontale",
                "La mindfulness riduce il volume dell'amigdala del 5 %",
                "Meditatori a lungo termine: 50 % in più di attività delle onde gamma",
                "La meditazione migliora la capacità di attenzione del 14 %",
                "12 min di pratica quotidiana mostrano cambiamenti cerebrali misurabili",
            ],
            [
                ("Quanta più attività prefrontale mostrano i meditatori?",
                 ["10 %", "15 %", "25 %", "35 %"], 2),
                ("Di quanto la mindfulness riduce il volume dell'amigdala?",
                 ["2 %", "5 %", "8 %", "12 %"], 1),
                ("Quanti minuti di meditazione quotidiana mostrano effetti misurabili?",
                 ["5 min", "8 min", "12 min", "20 min"], 2),
            ],
        ),
        (
            "Bilinguismo e cognizione",
            [
                "I bilingui cambiano compito 4,5 volte più velocemente",
                "L'insorgenza della demenza è ritardata di 4–5 anni nei bilingui",
                "I cervelli bilingui hanno materia grigia più densa nel CCA",
                "Controllo esecutivo: 15 % migliore nei bilingui",
                "Periodo critico per l'acquisizione linguistica: prima dei 7 anni",
                "I bilingui mostrano capacità superiore di memoria di lavoro",
            ],
            [
                ("Quanto più velocemente i bilingui cambiano compito?",
                 ["2,5×", "3,5×", "4,5×", "5,5×"], 2),
                ("Di quanti anni il bilinguismo ritarda la demenza?",
                 ["1–2 anni", "2–3 anni", "4–5 anni", "6–7 anni"], 2),
                ("Fino a che età dura il periodo critico per le lingue?",
                 ["5 anni", "7 anni", "10 anni", "12 anni"], 1),
            ],
        ),
    ],
    "humor": [
        (
            "La scienza della risata",
            [
                "Un adulto medio ride 17 volte al giorno",
                "Ridere brucia 10–40 calorie in 15 minuti",
                "I neonati iniziano a ridere verso i 4 mesi",
                "La risata rilascia endorfine e riduce il cortisolo del 39 %",
                "Gelotologia: lo studio scientifico della risata",
                "La risata è contagiosa — 30× più probabile in gruppo",
            ],
            [
                ("Quante volte ride un adulto medio al giorno?",
                 ["7 volte", "12 volte", "17 volte", "25 volte"], 2),
                ("Di quanto la risata riduce il cortisolo?",
                 ["19 %", "29 %", "39 %", "49 %"], 2),
                ("Come si chiama la scienza della risata?",
                 ["Umorologia", "Gelotologia", "Risologia", "Comicologia"], 1),
            ],
        ),
        (
            "Fatti curiosi sugli animali",
            [
                "I polpi hanno 3 cuori e sangue blu",
                "Un colibrì pesa meno di una moneta da 5 centesimi",
                "Le mucche hanno migliori amiche e si stressano senza di loro",
                "I delfini dormono con un occhio aperto",
                "I fenicotteri sono rosa solo per la loro dieta di gamberetti",
                "I bradipi impiegano 2 settimane per digerire il cibo",
            ],
            [
                ("Quanti cuori ha un polpo?",
                 ["1", "2", "3", "4"], 2),
                ("Perché i fenicotteri sono rosa?",
                 ["Genetica", "Luce solare", "Dieta di gamberetti", "Chimica dell'acqua"], 2),
                ("Quanto impiegano i bradipi a digerire?",
                 ["3 giorni", "1 settimana", "2 settimane", "1 mese"], 2),
            ],
        ),
        (
            "Record mondiali assurdi",
            [
                "Singhiozzo più lungo: 68 anni (Charles Osborne)",
                "Più magliette indossate contemporaneamente: 260",
                "Corsa all'indietro più veloce: 100 m in 13,6 secondi",
                "Unghia più lunga mai misurata: 8,65 metri",
                "Più hot dog mangiati in 10 min: 76",
                "Russamento più forte misurato: 93 decibel",
            ],
            [
                ("Quanto è durato il singhiozzo più lungo?",
                 ["12 anni", "34 anni", "68 anni", "85 anni"], 2),
                ("Quante magliette indossate contemporaneamente?",
                 ["120", "185", "260", "340"], 2),
                ("Quanto era forte il russamento più forte misurato?",
                 ["73 dB", "83 dB", "93 dB", "103 dB"], 2),
            ],
        ),
        (
            "Curiosità alimentari",
            [
                "Il miele non scade mai — miele di 3.000 anni era ancora commestibile",
                "Le banane sono botanicamente bacche, le fragole no",
                "Il ketchup veniva venduto come medicina negli anni 1830",
                "Un umano medio mangia 35 tonnellate di cibo nella vita",
                "Il wasabi al ristorante è di solito rafano colorato",
                "Un ananas impiega 2–3 anni per crescere",
            ],
            [
                ("Quanti anni aveva il miele più vecchio ancora commestibile?",
                 ["500 anni", "1.000 anni", "3.000 anni", "5.000 anni"], 2),
                ("Quanto cibo mangia un umano medio nella vita?",
                 ["15 tonnellate", "25 tonnellate", "35 tonnellate", "50 tonnellate"], 2),
                ("Quanto impiega un ananas a crescere?",
                 ["6 mesi", "1 anno", "2–3 anni", "5 anni"], 2),
            ],
        ),
        (
            "Inutile ma vero",
            [
                "Un fulmine è 5× più caldo della superficie del Sole",
                "La Terra ruota a 1.670 km/h all'equatore",
                "Le ossa umane sono più forti dell'acciaio (a parità di peso)",
                "Ci sono più stelle nell'universo che granelli di sabbia sulla Terra",
                "Lo stomaco rinnova la sua mucosa ogni 3–4 giorni",
                "L'Università di Oxford è più antica dell'Impero azteco",
            ],
            [
                ("Quanto è più caldo un fulmine rispetto alla superficie del Sole?",
                 ["2×", "3×", "5×", "8×"], 2),
                ("A che velocità ruota la Terra all'equatore?",
                 ["670 km/h", "1.070 km/h", "1.670 km/h", "2.270 km/h"], 2),
                ("Ogni quanto si rinnova la mucosa dello stomaco?",
                 ["Ogni 1–2 giorni", "Ogni 3–4 giorni", "Ogni 7 giorni", "Ogni 14 giorni"], 1),
            ],
        ),
    ],
    "history": [
        (
            "L'Antica Roma",
            [
                "Fondazione: 753 a.C. (secondo la leggenda)",
                "Popolazione massima: 1 milione (I secolo d.C.)",
                "Rete stradale: 400.000 km in tutto l'impero",
                "Il Colosseo ospitava 50.000–80.000 spettatori",
                "Gli acquedotti trasportavano 1 milione di m³ d'acqua al giorno",
                "L'Impero durò oltre 1.000 anni (753 a.C. – 476 d.C.)",
            ],
            [
                ("Quando fu fondata Roma secondo la leggenda?",
                 ["509 a.C.", "753 a.C.", "264 a.C.", "1.000 a.C."], 1),
                ("Quanti spettatori ospitava il Colosseo?",
                 ["20.000–30.000", "35.000–45.000", "50.000–80.000", "90.000–100.000"], 2),
                ("Quanto era lunga la rete stradale romana?",
                 ["100.000 km", "250.000 km", "400.000 km", "600.000 km"], 2),
            ],
        ),
        (
            "L'allunaggio",
            [
                "Data: 20 luglio 1969 (Apollo 11)",
                "Prime parole sulla Luna: Neil Armstrong",
                "Durata della missione: 8 giorni 3 ore 18 minuti",
                "Distanza Terra–Luna: 384.400 km",
                "Rocce lunari riportate: 21,55 kg",
                "Costo stimato: 25,4 miliardi $ (dollari del 1973)",
            ],
            [
                ("Quando avvenne il primo allunaggio?",
                 ["15 marzo 1968", "20 luglio 1969", "12 aprile 1970", "3 giugno 1971"], 1),
                ("Quante rocce lunari furono riportate?",
                 ["8,2 kg", "15,3 kg", "21,55 kg", "34,7 kg"], 2),
                ("Qual è la distanza Terra–Luna?",
                 ["284.400 km", "384.400 km", "484.400 km", "584.400 km"], 1),
            ],
        ),
        (
            "Seconda Guerra Mondiale — Cifre chiave",
            [
                "Durata: 1939–1945 (6 anni)",
                "Nazioni coinvolte: oltre 30",
                "Vittime totali stimate: 70–85 milioni",
                "D-Day: 6 giugno 1944 — 156.000 soldati alleati",
                "Costo: stimato 1.657 miliardi $ (dollari del 1945)",
                "Fine in Europa: 8 maggio 1945 (V-E Day)",
            ],
            [
                ("Quante nazioni furono coinvolte nella 2ª Guerra Mondiale?",
                 ["Oltre 10", "Oltre 20", "Oltre 30", "Oltre 50"], 2),
                ("Quanti soldati alleati sbarcarono il D-Day?",
                 ["75.000", "120.000", "156.000", "200.000"], 2),
                ("Quando finì la guerra in Europa?",
                 ["8 maggio 1945", "2 settembre 1945", "15 agosto 1945", "11 novembre 1944"], 0),
            ],
        ),
        (
            "Il Rinascimento",
            [
                "Periodo: circa 1350–1600 d.C.",
                "Origine: Firenze, Italia",
                "Leonardo da Vinci dipinse la Gioconda circa 1503–1519",
                "La stampa di Gutenberg: circa 1440",
                "Il soffitto della Cappella Sistina di Michelangelo: 1508–1512",
                "Popolazione europea: ~60 milioni dopo la peste",
            ],
            [
                ("Dove iniziò il Rinascimento?",
                 ["Parigi", "Roma", "Firenze", "Venezia"], 2),
                ("Quando Gutenberg inventò la stampa?",
                 ["circa 1380", "circa 1440", "circa 1500", "circa 1550"], 1),
                ("Quanto impiegò Michelangelo a dipingere il soffitto della Sistina?",
                 ["1 anno", "2 anni", "4 anni", "8 anni"], 2),
            ],
        ),
        (
            "La Rivoluzione Industriale",
            [
                "Inizio: circa 1760 in Gran Bretagna",
                "Macchina a vapore di Watt: brevettata nel 1769",
                "Prima ferrovia: Stockton–Darlington nel 1825",
                "Popolazione urbana cresciuta dal 20 % al 50 % entro il 1850",
                "Lavoro minorile: bambini dai 5 anni lavoravano turni di 16 ore",
                "La produzione di cotone aumentò dell'800 % tra il 1770 e il 1800",
            ],
            [
                ("Dove iniziò la Rivoluzione Industriale?",
                 ["Francia", "Germania", "Gran Bretagna", "USA"], 2),
                ("Quando fu brevettata la macchina a vapore di Watt?",
                 ["1745", "1769", "1785", "1801"], 1),
                ("Di quanto aumentò la produzione di cotone 1770–1800?",
                 ["200 %", "400 %", "800 %", "1.200 %"], 2),
            ],
        ),
    ],
    "nutrition": [
        (
            "Macronutrienti",
            [
                "Carboidrati: 4 calorie per grammo",
                "Proteine: 4 calorie per grammo",
                "Grassi: 9 calorie per grammo",
                "Distribuzione raccomandata: 45–65 % carboidrati, 20–35 % grassi, 10–35 % proteine",
                "Fibre: 25–30 g al giorno raccomandati",
                "Un adulto medio necessita di 2.000–2.500 kcal/giorno",
            ],
            [
                ("Quante calorie ha un grammo di grassi?",
                 ["4", "7", "9", "12"], 2),
                ("Quante fibre al giorno sono raccomandate?",
                 ["10–15 g", "15–20 g", "25–30 g", "35–40 g"], 2),
                ("Quale percentuale di calorie dovrebbe provenire dai carboidrati?",
                 ["25–40 %", "45–65 %", "60–80 %", "70–90 %"], 1),
            ],
        ),
        (
            "Fatti sull'idratazione",
            [
                "Corpo umano: 60 % di acqua",
                "Cervello e cuore: 73 % di acqua",
                "Assunzione raccomandata: 2,7–3,7 litri/giorno (cibo incluso)",
                "Il 2 % di disidratazione riduce le prestazioni cognitive del 25 %",
                "I reni filtrano 180 litri di sangue al giorno",
                "La caffeina è un diuretico lieve — l'effetto netto è minimo",
            ],
            [
                ("Quale percentuale del corpo è acqua?",
                 ["45 %", "52 %", "60 %", "70 %"], 2),
                ("Di quanto il 2 % di disidratazione riduce le prestazioni cognitive?",
                 ["10 %", "15 %", "25 %", "35 %"], 2),
                ("Quanti litri di sangue filtrano i reni al giorno?",
                 ["90 litri", "120 litri", "180 litri", "240 litri"], 2),
            ],
        ),
        (
            "Vitamine e minerali",
            [
                "Vitamina D: 1 miliardo di persone nel mondo sono carenti",
                "Ferro: il 25 % della popolazione mondiale ha carenza di ferro",
                "Vitamina C: 90 mg/giorno raccomandati per gli adulti",
                "Calcio: il 99 % è immagazzinato in ossa e denti",
                "B12: presente naturalmente solo nei prodotti animali",
                "Zinco: supporta oltre 300 reazioni enzimatiche",
            ],
            [
                ("Quante persone sono carenti di vitamina D nel mondo?",
                 ["100 milioni", "500 milioni", "1 miliardo", "2 miliardi"], 2),
                ("Quanta vitamina C al giorno è raccomandata?",
                 ["45 mg", "60 mg", "90 mg", "120 mg"], 2),
                ("Quale percentuale del calcio è in ossa e denti?",
                 ["85 %", "92 %", "99 %", "100 %"], 2),
            ],
        ),
        (
            "Connessione intestino-cervello",
            [
                "L'intestino contiene 500 milioni di neuroni",
                "Il 95 % della serotonina è prodotta nell'intestino",
                "Microbioma intestinale: 100 trilioni di batteri",
                "Nervo vago: connessione diretta tra intestino e cervello",
                "La salute intestinale influenza umore, sonno e cognizione",
                "I probiotici possono ridurre i sintomi d'ansia del 20 %",
            ],
            [
                ("Quanti neuroni contiene l'intestino?",
                 ["100 milioni", "300 milioni", "500 milioni", "800 milioni"], 2),
                ("Quale percentuale della serotonina è prodotta nell'intestino?",
                 ["50 %", "75 %", "85 %", "95 %"], 3),
                ("Di quanto i probiotici possono ridurre i sintomi d'ansia?",
                 ["10 %", "15 %", "20 %", "30 %"], 2),
            ],
        ),
        (
            "Caffeina e prestazione",
            [
                "La caffeina blocca i recettori dell'adenosina nel cervello",
                "Inizio dell'effetto: 15–45 minuti dopo l'assunzione",
                "Emivita: 5–6 ore in media",
                "Dose ottimale: 3–6 mg/kg di peso corporeo",
                "Migliora il tempo di reazione dell'11 %",
                "Dose giornaliera sicura: fino a 400 mg (circa 4 tazze di caffè)",
            ],
            [
                ("Quanto tempo impiega la caffeina a fare effetto?",
                 ["5–10 min", "15–45 min", "60–90 min", "2–3 ore"], 1),
                ("Di quanto la caffeina migliora il tempo di reazione?",
                 ["5 %", "8 %", "11 %", "15 %"], 2),
                ("Quanta caffeina al giorno è considerata sicura?",
                 ["200 mg", "300 mg", "400 mg", "500 mg"], 2),
            ],
        ),
    ],
}
