"""Spanish slide library for Slide Processing exercise."""

SLIDE_LIBRARY = {
    "science": [
        (
            "El cerebro humano",
            [
                "Peso: 1,4 kg (aproximadamente el 2 % del peso corporal)",
                "Contiene aproximadamente 86 mil millones de neuronas",
                "Usa el 20 % de la energía total del cuerpo",
                "Genera unos 23 vatios de potencia eléctrica",
                "Velocidad de procesamiento: hasta 120 m/s",
                "Capacidad de almacenamiento estimada en 2,5 petabytes",
            ],
            [
                ("¿Cuántas neuronas contiene el cerebro?",
                 ["12 mil millones", "86 mil millones", "100 mil millones", "45 mil millones"], 1),
                ("¿Qué porcentaje de energía corporal usa el cerebro?",
                 ["10 %", "15 %", "20 %", "30 %"], 2),
                ("¿Cuál es la capacidad de almacenamiento estimada?",
                 ["1,5 petabytes", "2,5 petabytes", "5 petabytes", "500 terabytes"], 1),
            ],
        ),
        (
            "Exploración de Marte",
            [
                "Distancia a la Tierra: 54,6 a 401 millones de km",
                "Temperatura superficial: −87 °C a −5 °C en promedio",
                "Olympus Mons: volcán más alto con 21,9 km",
                "Duración del día (sol): 24 horas 37 minutos",
                "Atmósfera: 95,3 % de dióxido de carbono",
                "Gravedad: 3,72 m/s² (38 % de la terrestre)",
            ],
            [
                ("¿Cuál es la altura del Olympus Mons?",
                 ["15,2 km", "18,6 km", "21,9 km", "25,1 km"], 2),
                ("¿Qué porcentaje de la atmósfera de Marte es CO₂?",
                 ["78,1 %", "89,7 %", "95,3 %", "99,2 %"], 2),
                ("¿Cuál es la gravedad de Marte comparada con la Tierra?",
                 ["28 %", "38 %", "48 %", "58 %"], 1),
            ],
        ),
        (
            "Datos sobre los océanos",
            [
                "Los océanos cubren el 71 % de la superficie terrestre",
                "Profundidad media: 3.688 metros",
                "Punto más profundo: Fosa de las Marianas con 10.994 m",
                "Contiene el 97 % del agua de la Tierra",
                "Océano Pacífico: el más grande con 165,25 millones de km²",
                "Temperatura del agua: −2 °C a 36 °C",
            ],
            [
                ("¿Cuál es la profundidad media del océano?",
                 ["2.450 m", "3.688 m", "4.200 m", "5.100 m"], 1),
                ("¿Qué porcentaje del agua terrestre está en los océanos?",
                 ["87 %", "92 %", "97 %", "99 %"], 2),
                ("¿Qué profundidad tiene la Fosa de las Marianas?",
                 ["8.848 m", "9.500 m", "10.994 m", "12.100 m"], 2),
            ],
        ),
        (
            "La velocidad de la luz",
            [
                "Velocidad en el vacío: 299.792.458 m/s",
                "La luz recorre 9,461 billones de km por año",
                "La luz solar llega a la Tierra en 8 min 20 s",
                "Luz de la Luna: 1,3 segundos hasta la Tierra",
                "Estrella más cercana (Próxima Centauri): 4,24 años luz",
                "La luz se reduce a 225.000 km/s en el agua",
            ],
            [
                ("¿Cuánto tarda la luz solar en llegar a la Tierra?",
                 ["4 min 10 s", "6 min 45 s", "8 min 20 s", "12 min 5 s"], 2),
                ("¿A qué distancia está Próxima Centauri en años luz?",
                 ["2,18", "4,24", "6,71", "8,60"], 1),
                ("¿Cuál es la velocidad de la luz en el agua?",
                 ["150.000 km/s", "225.000 km/s", "275.000 km/s", "299.792 km/s"], 1),
            ],
        ),
        (
            "ADN y genética",
            [
                "Genoma humano: 3.200 millones de pares de bases",
                "Los humanos comparten el 98,7 % del ADN con los chimpancés",
                "Cada célula contiene unos 2 metros de ADN",
                "Solo el 1,5 % del ADN codifica proteínas",
                "23 pares de cromosomas en las células humanas",
                "Velocidad de replicación del ADN: 1.000 nucleótidos/segundo",
            ],
            [
                ("¿Cuántos pares de bases tiene el genoma humano?",
                 ["1.800 millones", "3.200 millones", "4.600 millones", "6.400 millones"], 1),
                ("¿Qué porcentaje del ADN codifica proteínas?",
                 ["1,5 %", "5 %", "10 %", "25 %"], 0),
                ("¿Cuánto ADN contiene cada célula?",
                 ["0,5 metros", "2 metros", "5 metros", "10 metros"], 1),
            ],
        ),
    ],
    "business": [
        (
            "Mercado mundial del café 2024",
            [
                "Valor del mercado: 495.200 millones de dólares",
                "Consumo anual: 10.500 millones de kg en todo el mundo",
                "Mayor productor: Brasil (37,4 % de la producción mundial)",
                "Precio medio por kg: 14,80 $ (arábica)",
                "Segmento de café de especialidad crece al 12,3 % TCAC",
                "Finlandia lidera el consumo per cápita: 12 kg/año",
            ],
            [
                ("¿Cuál es el valor del mercado mundial del café?",
                 ["312.800 M $", "495.200 M $", "620.500 M $", "780.100 M $"], 1),
                ("¿Qué porcentaje del café mundial produce Brasil?",
                 ["22,1 %", "29,8 %", "37,4 %", "45,6 %"], 2),
                ("¿Qué país lidera el consumo de café per cápita?",
                 ["Italia", "Colombia", "Finlandia", "EE. UU."], 2),
            ],
        ),
        (
            "Ventas de vehículos eléctricos",
            [
                "Ventas globales de VE 2024: 17,1 millones de unidades",
                "Cuota de mercado: 22 % de todas las ventas de coches nuevos",
                "China lidera con el 59 % de las ventas globales de VE",
                "Coste medio de batería VE: 139 $/kWh",
                "Cuota de mercado de Tesla: 18,4 % de los VE globales",
                "Autonomía media de VE: 348 km por carga",
            ],
            [
                ("¿Cuántos VE se vendieron en el mundo en 2024?",
                 ["9,8 millones", "13,5 millones", "17,1 millones", "21,4 millones"], 2),
                ("¿Cuál es la cuota de China en ventas globales de VE?",
                 ["35 %", "47 %", "59 %", "72 %"], 2),
                ("¿Cuál es el coste medio de batería VE por kWh?",
                 ["89 $", "139 $", "189 $", "239 $"], 1),
            ],
        ),
        (
            "Estadísticas del teletrabajo",
            [
                "32,6 millones de estadounidenses trabajarán en remoto en 2025",
                "Aumento de productividad: 13 % para teletrabajadores",
                "Tiempo de desplazamiento ahorrado: 72 minutos/día",
                "Las empresas ahorran 11.000 $ por teletrabajador/año",
                "El 67 % reporta mejor equilibrio vida-trabajo",
                "Mercado de videoconferencias: 13.800 millones de dólares",
            ],
            [
                ("¿Cuánto tiempo de desplazamiento ahorran los teletrabajadores?",
                 ["45 minutos", "72 minutos", "90 minutos", "120 minutos"], 1),
                ("¿Cuánto ahorran las empresas por teletrabajador?",
                 ["5.000 $", "8.500 $", "11.000 $", "15.000 $"], 2),
                ("¿Cuál es el aumento de productividad en teletrabajo?",
                 ["8 %", "13 %", "18 %", "25 %"], 1),
            ],
        ),
        (
            "Mercado de smartphones T4 2024",
            [
                "Envíos globales: 328,2 millones de unidades",
                "Samsung: 19,4 % de cuota de mercado (n.º 1)",
                "Apple: 18,2 % de cuota de mercado (n.º 2)",
                "Precio medio de venta: 322 $",
                "Teléfonos 5G: 78 % de todos los envíos",
                "Teléfonos plegables crecieron un 49 % interanual",
            ],
            [
                ("¿Cuántos smartphones se enviaron en el T4 2024?",
                 ["245,6 millones", "328,2 millones", "412,7 millones", "501,3 millones"], 1),
                ("¿Cuál fue la cuota de mercado de Samsung?",
                 ["15,8 %", "19,4 %", "23,1 %", "27,6 %"], 1),
                ("¿Qué porcentaje de envíos fueron teléfonos 5G?",
                 ["58 %", "68 %", "78 %", "88 %"], 2),
            ],
        ),
        (
            "Turismo mundial 2024",
            [
                "Llegadas internacionales: 1.400 millones",
                "Ingresos por turismo: 1,9 billones de dólares",
                "País más visitado: Francia (100 millones de visitantes)",
                "Gasto medio por turista: 1.350 $",
                "El turismo emplea a 330 millones de personas en el mundo",
                "Crecimiento Asia-Pacífico: 18 % interanual",
            ],
            [
                ("¿Cuántas llegadas turísticas internacionales hubo en 2024?",
                 ["800 millones", "1.100 millones", "1.400 millones", "1.800 millones"], 2),
                ("¿Qué país tuvo más visitantes?",
                 ["España", "EE. UU.", "Francia", "Italia"], 2),
                ("¿Cuántas personas emplea el turismo en el mundo?",
                 ["180 millones", "250 millones", "330 millones", "420 millones"], 2),
            ],
        ),
    ],
    "geography": [
        (
            "Japón",
            [
                "Población: 123,3 millones (2024)",
                "Capital: Tokio (13,96 millones de habitantes)",
                "Superficie: 377.975 km²",
                "Punto más alto: Monte Fuji con 3.776 metros",
                "PIB per cápita: 33.950 $",
                "Esperanza de vida: 84,8 años (la más alta del mundo)",
            ],
            [
                ("¿Cuál es la población de Japón?",
                 ["98,5 millones", "123,3 millones", "145,7 millones", "168,2 millones"], 1),
                ("¿Cuál es la altura del Monte Fuji?",
                 ["2.954 m", "3.776 m", "4.421 m", "5.108 m"], 1),
                ("¿Cuál es la esperanza de vida en Japón?",
                 ["78,2 años", "81,5 años", "84,8 años", "87,3 años"], 2),
            ],
        ),
        (
            "Brasil",
            [
                "Población: 216,4 millones (2024)",
                "Capital: Brasilia (no São Paulo ni Río)",
                "Superficie: 8.515.767 km² (5.º país más grande)",
                "Selva amazónica: 5,5 millones de km²",
                "Idioma oficial: portugués",
                "Costa: 7.491 km de largo",
            ],
            [
                ("¿Cuál es la capital de Brasil?",
                 ["São Paulo", "Río de Janeiro", "Brasilia", "Salvador"], 2),
                ("¿Cuál es la superficie de la selva amazónica?",
                 ["3,2 M km²", "5,5 M km²", "7,8 M km²", "9,1 M km²"], 1),
                ("¿Cuánto mide la costa de Brasil?",
                 ["4.230 km", "5.860 km", "7.491 km", "9.120 km"], 2),
            ],
        ),
        (
            "Australia",
            [
                "Población: 26,6 millones (2024)",
                "Capital: Canberra (no Sídney)",
                "Superficie: 7.692.024 km² (6.º país más grande)",
                "Gran Barrera de Coral: 2.300 km de largo",
                "Punto más alto: Monte Kosciuszko con 2.228 m",
                "El 87 % de la población vive en zonas urbanas",
            ],
            [
                ("¿Cuál es la población de Australia?",
                 ["18,4 millones", "26,6 millones", "34,2 millones", "42,8 millones"], 1),
                ("¿Cuánto mide la Gran Barrera de Coral?",
                 ["1.200 km", "1.800 km", "2.300 km", "2.900 km"], 2),
                ("¿Qué porcentaje de australianos vive en zonas urbanas?",
                 ["72 %", "79 %", "87 %", "94 %"], 2),
            ],
        ),
        (
            "Suiza",
            [
                "Población: 8,9 millones (2024)",
                "Capital: Berna (no Zúrich ni Ginebra)",
                "4 idiomas oficiales: alemán, francés, italiano, romanche",
                "Superficie: 41.285 km²",
                "Punto más alto: Punta Dufour con 4.634 m",
                "PIB per cápita: 99.994 $ (2.º más alto del mundo)",
            ],
            [
                ("¿Cuál es la capital de Suiza?",
                 ["Zúrich", "Ginebra", "Berna", "Basilea"], 2),
                ("¿Cuántos idiomas oficiales tiene Suiza?",
                 ["2", "3", "4", "5"], 2),
                ("¿Cuál es el PIB per cápita de Suiza?",
                 ["67.450 $", "82.310 $", "99.994 $", "115.200 $"], 2),
            ],
        ),
        (
            "Egipto",
            [
                "Población: 109,3 millones (2024)",
                "Capital: El Cairo (21,9 millones de habitantes)",
                "Río Nilo: 6.650 km (el más largo de África)",
                "Gran Pirámide: 146,6 metros de alto (originalmente)",
                "Superficie: 1.002.450 km² (97 % desierto)",
                "Canal de Suez: 193,3 km de largo, inaugurado en 1869",
            ],
            [
                ("¿Cuál es la población de El Cairo?",
                 ["14,2 millones", "17,5 millones", "21,9 millones", "25,3 millones"], 2),
                ("¿Cuánto mide el río Nilo?",
                 ["4.130 km", "5.390 km", "6.650 km", "7.920 km"], 2),
                ("¿Cuánto mide el Canal de Suez?",
                 ["120,5 km", "156,8 km", "193,3 km", "231,7 km"], 2),
            ],
        ),
    ],
    "motivation": [
        (
            "La regla de las 10.000 horas",
            [
                "Popularizada por Malcolm Gladwell en Outliers (2008)",
                "Basada en la investigación de K. Anders Ericsson",
                "Violinistas de élite promediaron 10.000 horas de práctica a los 20 años",
                "La práctica deliberada importa más que las horas totales",
                "Los mejores practican 4 horas/día con concentración total",
                "Los ciclos de retroalimentación aceleran el aprendizaje un 26 %",
            ],
            [
                ("¿Quién popularizó la regla de las 10.000 horas?",
                 ["Daniel Kahneman", "Malcolm Gladwell", "Cal Newport", "James Clear"], 1),
                ("¿Cuántas horas/día practican los mejores?",
                 ["2 horas", "4 horas", "6 horas", "8 horas"], 1),
                ("¿Cuánto aceleran los ciclos de retroalimentación el aprendizaje?",
                 ["12 %", "18 %", "26 %", "35 %"], 2),
            ],
        ),
        (
            "Investigación sobre mentalidad de crecimiento",
            [
                "Acuñado por Carol Dweck en la Universidad de Stanford",
                "Los alumnos elogiados por el esfuerzo mejoraron un 30 % más",
                "Mentalidad fija: la inteligencia es estática",
                "Mentalidad de crecimiento: las habilidades se desarrollan con dedicación",
                "El 73 % de los principales CEO se identifican con mentalidad de crecimiento",
                "Las intervenciones de mentalidad elevaron las notas 0,3 puntos",
            ],
            [
                ("¿Quién acuñó el término 'mentalidad de crecimiento'?",
                 ["Angela Duckworth", "Carol Dweck", "Martin Seligman", "Amy Cuddy"], 1),
                ("¿Cuánto más mejoraron los alumnos elogiados por el esfuerzo?",
                 ["10 %", "20 %", "30 %", "40 %"], 2),
                ("¿Qué porcentaje de los principales CEO tienen mentalidad de crecimiento?",
                 ["53 %", "63 %", "73 %", "83 %"], 2),
            ],
        ),
        (
            "El poder de los hábitos",
            [
                "El 40 % de las acciones diarias son hábitos",
                "Bucle de hábito: señal → rutina → recompensa (Duhigg)",
                "Formar un nuevo hábito toma 66 días en promedio",
                "Las intenciones de implementación aumentan el éxito un 91 %",
                "Los hábitos clave desencadenan cambios positivos en cascada",
                "Apilamiento de hábitos: vincular nuevos hábitos a los existentes",
            ],
            [
                ("¿Qué porcentaje de las acciones diarias son hábitos?",
                 ["20 %", "30 %", "40 %", "50 %"], 2),
                ("¿Cuántos días toma formar un nuevo hábito en promedio?",
                 ["21 días", "45 días", "66 días", "90 días"], 2),
                ("¿Cuánto aumentan las intenciones de implementación el éxito?",
                 ["51 %", "71 %", "81 %", "91 %"], 3),
            ],
        ),
        (
            "Estado de flow y rendimiento",
            [
                "Concepto desarrollado por Mihaly Csikszentmihalyi en 1975",
                "El flow aumenta la productividad hasta un 500 %",
                "Requiere equilibrio desafío-habilidad (4 % por encima del nivel actual)",
                "Tiempo medio para entrar en flow: 15–20 minutos",
                "Las interrupciones reinician completamente el temporizador de flow",
                "El flow activa 5 neuroquímicos: dopamina, noradrenalina, endorfinas, anandamida, serotonina",
            ],
            [
                ("¿Quién desarrolló el concepto de flow?",
                 ["Daniel Pink", "Mihaly Csikszentmihalyi", "Cal Newport", "Adam Grant"], 1),
                ("¿Cuánto puede aumentar el flow la productividad?",
                 ["100 %", "200 %", "350 %", "500 %"], 3),
                ("¿Cuánto tiempo se tarda en entrar en flow?",
                 ["5–10 minutos", "15–20 minutos", "25–30 minutos", "35–40 minutos"], 1),
            ],
        ),
        (
            "Determinación y perseverancia",
            [
                "Investigada por Angela Duckworth en UPenn",
                "La determinación predice el éxito mejor que el CI en el 78 % de los estudios",
                "Cadetes de West Point: la puntuación de determinación predijo la tasa de finalización",
                "Determinación = pasión + persistencia sostenida durante años",
                "Las personas determinadas practican un 32 % más de horas semanales",
                "La determinación se puede desarrollar — no es puramente innata",
            ],
            [
                ("¿Quién investigó la determinación?",
                 ["Carol Dweck", "Angela Duckworth", "Martin Seligman", "Dan Pink"], 1),
                ("¿En qué porcentaje de estudios la determinación supera al CI?",
                 ["58 %", "68 %", "78 %", "88 %"], 2),
                ("¿Cuánto más practican las personas determinadas semanalmente?",
                 ["12 %", "22 %", "32 %", "42 %"], 2),
            ],
        ),
    ],
    "neuroplasticity": [
        (
            "Bases de la neuroplasticidad",
            [
                "El cerebro forma 1 millón de nuevas conexiones/segundo en la infancia",
                "Los adultos generan ~700 nuevas neuronas/día en el hipocampo",
                "Los taxistas de Londres tienen hipocampos posteriores un 16 % más grandes",
                "La neuroplasticidad alcanza su máximo antes de los 25 años",
                "Aprender una nueva habilidad aumenta la materia gris en 2 semanas",
                "El sueño consolida las vías neuronales — 7–9 horas óptimas",
            ],
            [
                ("¿Cuántas neuronas nuevas generan los adultos diariamente?",
                 ["200", "500", "700", "1.000"], 2),
                ("¿Cuánto más grandes son los hipocampos de los taxistas?",
                 ["8 %", "12 %", "16 %", "22 %"], 2),
                ("¿En cuánto tiempo el aprendizaje aumenta la materia gris?",
                 ["2 días", "2 semanas", "2 meses", "6 meses"], 1),
            ],
        ),
        (
            "Formación de la memoria",
            [
                "La memoria a corto plazo dura 15–30 segundos sin repetición",
                "Capacidad de la memoria de trabajo: 4 ± 1 elementos",
                "Consolidación: el hipocampo transfiere al neocórtex durante el sueño",
                "La repetición espaciada mejora la retención un 200 %",
                "Los recuerdos emocionales son 3× más fuertes (participación de la amígdala)",
                "La técnica del palacio de la memoria mejora el recuerdo un 80 %",
            ],
            [
                ("¿Cuánto dura la memoria a corto plazo sin repetición?",
                 ["5–10 s", "15–30 s", "45–60 s", "2–3 min"], 1),
                ("¿Cuánto mejora la repetición espaciada la retención?",
                 ["50 %", "100 %", "200 %", "300 %"], 2),
                ("¿Cuánto mejora el palacio de la memoria el recuerdo?",
                 ["40 %", "60 %", "80 %", "100 %"], 2),
            ],
        ),
        (
            "Ejercicio y cerebro",
            [
                "30 min de aeróbico aumentan el BDNF un 32 %",
                "El ejercicio regular agranda el hipocampo un 2 %",
                "El ejercicio mejora las funciones ejecutivas un 20 %",
                "Beneficios cognitivos óptimos: 150 min de ejercicio moderado/semana",
                "El ejercicio después de aprender mejora la retención un 10 %",
                "La forma física reduce el riesgo de demencia un 30 %",
            ],
            [
                ("¿Cuánto aumenta 30 min de aeróbico el BDNF?",
                 ["12 %", "22 %", "32 %", "42 %"], 2),
                ("¿Cuánto agranda el ejercicio el hipocampo?",
                 ["0,5 %", "1 %", "2 %", "4 %"], 2),
                ("¿Cuántos minutos de ejercicio moderado por semana son óptimos?",
                 ["60 min", "90 min", "150 min", "200 min"], 2),
            ],
        ),
        (
            "Meditación y cambios neuronales",
            [
                "8 semanas de meditación aumentan la densidad de materia gris",
                "Los meditadores muestran un 25 % más de actividad en el córtex prefrontal",
                "La atención plena reduce el volumen de la amígdala un 5 %",
                "Meditadores a largo plazo: 50 % más de actividad de ondas gamma",
                "La meditación mejora la capacidad de atención un 14 %",
                "12 min de práctica diaria muestran cambios cerebrales medibles",
            ],
            [
                ("¿Cuánta más actividad prefrontal muestran los meditadores?",
                 ["10 %", "15 %", "25 %", "35 %"], 2),
                ("¿Cuánto reduce la atención plena el volumen de la amígdala?",
                 ["2 %", "5 %", "8 %", "12 %"], 1),
                ("¿Cuántos minutos de meditación diaria muestran efectos medibles?",
                 ["5 min", "8 min", "12 min", "20 min"], 2),
            ],
        ),
        (
            "Bilingüismo y cognición",
            [
                "Los bilingües cambian de tarea 4,5 veces más rápido",
                "La aparición de demencia se retrasa 4–5 años en bilingües",
                "Los cerebros bilingües tienen materia gris más densa en el CCA",
                "Control ejecutivo: 15 % mejor en bilingües",
                "Período crítico para la adquisición del lenguaje: antes de los 7 años",
                "Los bilingües muestran capacidad superior de memoria de trabajo",
            ],
            [
                ("¿Cuánto más rápido cambian de tarea los bilingües?",
                 ["2,5×", "3,5×", "4,5×", "5,5×"], 2),
                ("¿Cuántos años retrasa el bilingüismo la aparición de demencia?",
                 ["1–2 años", "2–3 años", "4–5 años", "6–7 años"], 2),
                ("¿Hasta qué edad dura el período crítico para los idiomas?",
                 ["5 años", "7 años", "10 años", "12 años"], 1),
            ],
        ),
    ],
    "humor": [
        (
            "La ciencia de la risa",
            [
                "Un adulto promedio ríe 17 veces al día",
                "Reír quema 10–40 calorías en 15 minutos",
                "Los bebés empiezan a reír a los 4 meses aproximadamente",
                "La risa libera endorfinas y reduce el cortisol un 39 %",
                "Gelotología: el estudio científico de la risa",
                "La risa es contagiosa — 30× más probable en grupo",
            ],
            [
                ("¿Cuántas veces ríe un adulto promedio al día?",
                 ["7 veces", "12 veces", "17 veces", "25 veces"], 2),
                ("¿Cuánto reduce la risa el cortisol?",
                 ["19 %", "29 %", "39 %", "49 %"], 2),
                ("¿Cómo se llama la ciencia de la risa?",
                 ["Humorología", "Gelotología", "Risología", "Comicología"], 1),
            ],
        ),
        (
            "Datos curiosos de animales",
            [
                "Los pulpos tienen 3 corazones y sangre azul",
                "Un colibrí pesa menos que una moneda de 5 céntimos",
                "Las vacas tienen mejores amigas y se estresan sin ellas",
                "Los delfines duermen con un ojo abierto",
                "Los flamencos solo son rosas por su dieta de camarones",
                "Los perezosos tardan 2 semanas en digerir la comida",
            ],
            [
                ("¿Cuántos corazones tiene un pulpo?",
                 ["1", "2", "3", "4"], 2),
                ("¿Por qué los flamencos son rosas?",
                 ["Genética", "Luz solar", "Dieta de camarones", "Química del agua"], 2),
                ("¿Cuánto tardan los perezosos en digerir?",
                 ["3 días", "1 semana", "2 semanas", "1 mes"], 2),
            ],
        ),
        (
            "Récords mundiales absurdos",
            [
                "Hipo más largo: 68 años (Charles Osborne)",
                "Más camisetas puestas a la vez: 260",
                "Carrera hacia atrás más rápida: 100 m en 13,6 segundos",
                "Uña más larga jamás medida: 8,65 metros",
                "Más perritos calientes comidos en 10 min: 76",
                "Ronquido más fuerte registrado: 93 decibelios",
            ],
            [
                ("¿Cuánto duró el hipo más largo?",
                 ["12 años", "34 años", "68 años", "85 años"], 2),
                ("¿Cuántas camisetas se pusieron a la vez?",
                 ["120", "185", "260", "340"], 2),
                ("¿Cuántos decibelios tenía el ronquido más fuerte?",
                 ["73 dB", "83 dB", "93 dB", "103 dB"], 2),
            ],
        ),
        (
            "Curiosidades alimentarias",
            [
                "La miel nunca caduca — miel de 3.000 años aún era comestible",
                "Los plátanos son botánicamente bayas, las fresas no",
                "El kétchup se vendía como medicina en la década de 1830",
                "Un humano promedio come 35 toneladas de comida en su vida",
                "El wasabi en restaurantes suele ser rábano picante coloreado",
                "Una piña tarda 2–3 años en crecer",
            ],
            [
                ("¿Qué antigüedad tenía la miel más vieja aún comestible?",
                 ["500 años", "1.000 años", "3.000 años", "5.000 años"], 2),
                ("¿Cuánta comida come un humano promedio en su vida?",
                 ["15 toneladas", "25 toneladas", "35 toneladas", "50 toneladas"], 2),
                ("¿Cuánto tarda una piña en crecer?",
                 ["6 meses", "1 año", "2–3 años", "5 años"], 2),
            ],
        ),
        (
            "Inútil pero cierto",
            [
                "Un rayo es 5× más caliente que la superficie del Sol",
                "La Tierra gira a 1.670 km/h en el ecuador",
                "Los huesos humanos son más fuertes que el acero (por peso)",
                "Hay más estrellas en el universo que granos de arena en la Tierra",
                "Tu estómago renueva su mucosa cada 3–4 días",
                "La Universidad de Oxford es más antigua que el Imperio azteca",
            ],
            [
                ("¿Cuánto más caliente es un rayo que la superficie del Sol?",
                 ["2×", "3×", "5×", "8×"], 2),
                ("¿A qué velocidad gira la Tierra en el ecuador?",
                 ["670 km/h", "1.070 km/h", "1.670 km/h", "2.270 km/h"], 2),
                ("¿Con qué frecuencia se renueva la mucosa del estómago?",
                 ["Cada 1–2 días", "Cada 3–4 días", "Cada 7 días", "Cada 14 días"], 1),
            ],
        ),
    ],
    "history": [
        (
            "La Antigua Roma",
            [
                "Fundación: 753 a. C. (según la leyenda)",
                "Población máxima: 1 millón (siglo I d. C.)",
                "Red de carreteras: 400.000 km en todo el imperio",
                "El Coliseo albergaba 50.000–80.000 espectadores",
                "Los acueductos transportaban 1 millón de m³ de agua al día",
                "El Imperio duró más de 1.000 años (753 a. C. – 476 d. C.)",
            ],
            [
                ("¿Cuándo se fundó Roma según la leyenda?",
                 ["509 a. C.", "753 a. C.", "264 a. C.", "1.000 a. C."], 1),
                ("¿Cuántos espectadores albergaba el Coliseo?",
                 ["20.000–30.000", "35.000–45.000", "50.000–80.000", "90.000–100.000"], 2),
                ("¿Cuánto medía la red de carreteras romana?",
                 ["100.000 km", "250.000 km", "400.000 km", "600.000 km"], 2),
            ],
        ),
        (
            "El alunizaje",
            [
                "Fecha: 20 de julio de 1969 (Apolo 11)",
                "Primeras palabras en la Luna: Neil Armstrong",
                "Duración de la misión: 8 días 3 horas 18 minutos",
                "Distancia Tierra–Luna: 384.400 km",
                "Rocas lunares traídas: 21,55 kg",
                "Coste estimado: 25.400 millones $ (dólares de 1973)",
            ],
            [
                ("¿Cuándo fue el primer alunizaje?",
                 ["15 de marzo de 1968", "20 de julio de 1969", "12 de abril de 1970", "3 de junio de 1971"], 1),
                ("¿Cuántas rocas lunares se trajeron?",
                 ["8,2 kg", "15,3 kg", "21,55 kg", "34,7 kg"], 2),
                ("¿Cuál es la distancia Tierra–Luna?",
                 ["284.400 km", "384.400 km", "484.400 km", "584.400 km"], 1),
            ],
        ),
        (
            "Segunda Guerra Mundial — Cifras clave",
            [
                "Duración: 1939–1945 (6 años)",
                "Naciones involucradas: más de 30",
                "Víctimas totales estimadas: 70–85 millones",
                "Día D: 6 de junio de 1944 — 156.000 soldados aliados",
                "Coste: estimado en 1,657 billones $ (dólares de 1945)",
                "Fin en Europa: 8 de mayo de 1945 (Día de la Victoria)",
            ],
            [
                ("¿Cuántas naciones participaron en la 2.ª Guerra Mundial?",
                 ["Más de 10", "Más de 20", "Más de 30", "Más de 50"], 2),
                ("¿Cuántos soldados aliados desembarcaron el Día D?",
                 ["75.000", "120.000", "156.000", "200.000"], 2),
                ("¿Cuándo terminó la guerra en Europa?",
                 ["8 de mayo de 1945", "2 de septiembre de 1945", "15 de agosto de 1945", "11 de noviembre de 1944"], 0),
            ],
        ),
        (
            "El Renacimiento",
            [
                "Período: aprox. 1350–1600 d. C.",
                "Origen: Florencia, Italia",
                "Leonardo da Vinci pintó la Mona Lisa aprox. 1503–1519",
                "La imprenta de Gutenberg: aprox. 1440",
                "El techo de la Capilla Sixtina de Miguel Ángel: 1508–1512",
                "Población de Europa: ~60 millones después de la peste",
            ],
            [
                ("¿Dónde comenzó el Renacimiento?",
                 ["París", "Roma", "Florencia", "Venecia"], 2),
                ("¿Cuándo inventó Gutenberg la imprenta?",
                 ["aprox. 1380", "aprox. 1440", "aprox. 1500", "aprox. 1550"], 1),
                ("¿Cuánto tardó Miguel Ángel en pintar el techo de la Sixtina?",
                 ["1 año", "2 años", "4 años", "8 años"], 2),
            ],
        ),
        (
            "La Revolución Industrial",
            [
                "Inicio: aprox. 1760 en Gran Bretaña",
                "Máquina de vapor de Watt: patentada en 1769",
                "Primer ferrocarril: Stockton–Darlington en 1825",
                "Población urbana creció del 20 % al 50 % para 1850",
                "Trabajo infantil: niños desde los 5 años trabajaban turnos de 16 horas",
                "La producción de algodón aumentó un 800 % entre 1770 y 1800",
            ],
            [
                ("¿Dónde comenzó la Revolución Industrial?",
                 ["Francia", "Alemania", "Gran Bretaña", "EE. UU."], 2),
                ("¿Cuándo se patentó la máquina de vapor de Watt?",
                 ["1745", "1769", "1785", "1801"], 1),
                ("¿Cuánto aumentó la producción de algodón 1770–1800?",
                 ["200 %", "400 %", "800 %", "1.200 %"], 2),
            ],
        ),
    ],
    "nutrition": [
        (
            "Macronutrientes",
            [
                "Carbohidratos: 4 calorías por gramo",
                "Proteínas: 4 calorías por gramo",
                "Grasas: 9 calorías por gramo",
                "Distribución recomendada: 45–65 % carbohidratos, 20–35 % grasas, 10–35 % proteínas",
                "Fibra: 25–30 g por día recomendados",
                "Un adulto promedio necesita 2.000–2.500 kcal/día",
            ],
            [
                ("¿Cuántas calorías tiene un gramo de grasa?",
                 ["4", "7", "9", "12"], 2),
                ("¿Cuánta fibra por día se recomienda?",
                 ["10–15 g", "15–20 g", "25–30 g", "35–40 g"], 2),
                ("¿Qué porcentaje de calorías debe provenir de carbohidratos?",
                 ["25–40 %", "45–65 %", "60–80 %", "70–90 %"], 1),
            ],
        ),
        (
            "Datos sobre hidratación",
            [
                "Cuerpo humano: 60 % de agua",
                "Cerebro y corazón: 73 % de agua",
                "Ingesta recomendada: 2,7–3,7 litros/día (incluyendo alimentos)",
                "Un 2 % de deshidratación reduce el rendimiento cognitivo un 25 %",
                "Los riñones filtran 180 litros de sangre al día",
                "La cafeína es un diurético leve — el efecto neto es mínimo",
            ],
            [
                ("¿Qué porcentaje del cuerpo es agua?",
                 ["45 %", "52 %", "60 %", "70 %"], 2),
                ("¿Cuánto reduce un 2 % de deshidratación el rendimiento cognitivo?",
                 ["10 %", "15 %", "25 %", "35 %"], 2),
                ("¿Cuántos litros de sangre filtran los riñones al día?",
                 ["90 litros", "120 litros", "180 litros", "240 litros"], 2),
            ],
        ),
        (
            "Vitaminas y minerales",
            [
                "Vitamina D: 1.000 millones de personas en el mundo tienen deficiencia",
                "Hierro: el 25 % de la población mundial tiene deficiencia de hierro",
                "Vitamina C: 90 mg/día recomendados para adultos",
                "Calcio: el 99 % está almacenado en huesos y dientes",
                "B12: solo se encuentra naturalmente en productos animales",
                "Zinc: apoya más de 300 reacciones enzimáticas",
            ],
            [
                ("¿Cuántas personas tienen deficiencia de vitamina D en el mundo?",
                 ["100 millones", "500 millones", "1.000 millones", "2.000 millones"], 2),
                ("¿Cuánta vitamina C por día se recomienda?",
                 ["45 mg", "60 mg", "90 mg", "120 mg"], 2),
                ("¿Qué porcentaje del calcio está en huesos y dientes?",
                 ["85 %", "92 %", "99 %", "100 %"], 2),
            ],
        ),
        (
            "Conexión intestino-cerebro",
            [
                "El intestino contiene 500 millones de neuronas",
                "El 95 % de la serotonina se produce en el intestino",
                "Microbioma intestinal: 100 billones de bacterias",
                "Nervio vago: conexión directa entre intestino y cerebro",
                "La salud intestinal influye en el ánimo, el sueño y la cognición",
                "Los probióticos pueden reducir los síntomas de ansiedad un 20 %",
            ],
            [
                ("¿Cuántas neuronas contiene el intestino?",
                 ["100 millones", "300 millones", "500 millones", "800 millones"], 2),
                ("¿Qué porcentaje de la serotonina se produce en el intestino?",
                 ["50 %", "75 %", "85 %", "95 %"], 3),
                ("¿Cuánto pueden reducir los probióticos los síntomas de ansiedad?",
                 ["10 %", "15 %", "20 %", "30 %"], 2),
            ],
        ),
        (
            "Cafeína y rendimiento",
            [
                "La cafeína bloquea los receptores de adenosina en el cerebro",
                "Inicio de efecto: 15–45 minutos después de la ingesta",
                "Vida media: 5–6 horas en promedio",
                "Dosis óptima: 3–6 mg/kg de peso corporal",
                "Mejora el tiempo de reacción un 11 %",
                "Dosis diaria segura: hasta 400 mg (unas 4 tazas de café)",
            ],
            [
                ("¿Cuánto tarda la cafeína en hacer efecto?",
                 ["5–10 min", "15–45 min", "60–90 min", "2–3 horas"], 1),
                ("¿Cuánto mejora la cafeína el tiempo de reacción?",
                 ["5 %", "8 %", "11 %", "15 %"], 2),
                ("¿Cuánta cafeína al día se considera segura?",
                 ["200 mg", "300 mg", "400 mg", "500 mg"], 2),
            ],
        ),
    ],
}
